### ISSUE TITLE
virtual keyboard hidden

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#872] opened 2021-03-26 15:12 UTC
## Description
On ipad pro 12.9 " and on ipad 9.7 ", virtual keyboard is hidden by native virtual keybord.
On Iphone X11 pro, it works fine (virtual mathlive keyboard is displayed).

## Steps to Reproduce

Try in mathlive.io homepage with the default mathfield.

### Environment

iOS, chrome and safati

**Comment by arnog** [comment] 2021-04-04 12:27
Duplicate of #818.

**Closed** 2021-04-04 12:28 UTC
