### ISSUE TITLE
mathlive.latexToAST("-x+5"); returns obj but instead of x is "undefined"

### ISSUE THREAD

**Issue by Kreijstal** [arnog/mathlive#221] opened 2019-06-26 04:53 UTC
if you execute `mathlive.latexToAST("-x+5");`

you might get
```
Object {
  fn: "+"
  arg: Array(2) [
  0: Object {
  fn: "-"
  arg: Array(1) [undefined]
}
  1: 5
]
}
```

As you can see, it ignores the existence of x or any other variable for that matter, why is this?

**Comment by arnog** [comment] 2019-06-26 16:42
I can't reproduce this with the current version. 

You can try it for yourself at https://mathlive.io/deploy/examples/basic/index.esm.html

Do you have a JSFiddle or some code somewhere that would show this problem? 
Are you sure you are using the current version of MathLive?

**Comment by arnog** [comment] 2019-06-26 16:42
Closing for now, but please re-open if you can get a reproducible example with the current version.

**Closed by arnog** 2019-06-26 16:42 UTC
Labels: unable to reproduce
