### ISSUE TITLE
Iframed VirtualKeyboard causes 'Uncaught RangeError: Maximum call stack size exceeded' after virtual-key-click

### ISSUE THREAD

**Issue by szn** [arnog/mathlive#2140] opened 2023-09-17 13:44 UTC
## Description

VirtualKeyboard rendered within an iframe causes `Uncaught RangeError: Maximum call stack size exceeded` after virtual-key-click.

## Steps to Reproduce

1. Create the simplest, editable math field in the `index.html` file:

```index.html
<!DOCTYPE html>
<html>
<body>
  <div id="formula"></div>
  <script type="module">
    window.addEventListener('DOMContentLoaded', () => 
      import('https://unpkg.com/mathlive?module').then((mathlive) => {
        const mfe = new mathlive.MathfieldElement();
        mfe.value = '\\frac{\\pi}{2}';
        mfe.mathVirtualKeyboardPolicy = 'sandboxed';
        document.getElementById("formula").appendChild(mfe);
      })
    );
  </script>
</body>
</html>
```

2. Create an iframe-wrapper in the `frame.html` file:

```frame.html
<!DOCTYPE html>
<html>
  <body>
    <iframe src="http://127.0.0.1:8000/" width="800" height="800" frameborder="0">
  </body>
</html>
```

3. Run a local HTTP server with `python3` (make sure you run this command in the same folder as two files created above):

```.sh
$ python3 -m http.server
```

4. Open the `frame.html` file locally. Open Virtual Keyboard.

5. Click on any virtual key (say '7').

### Actual Behavior

You'll see the digit repeated in the math field up to the field limit. Console logs show:

```log
Uncaught RangeError: Maximum call stack size exceeded.
    at t.sendMessage (mathlive.min.mjs?module:2264:21180)
    at t.executeCommand (mathlive.min.mjs?module:2264:22864)
    at t.handleMessage (mathlive.min.mjs?module:2264:20215)
    at t.handleEvent (mathlive.min.mjs?module:2264:19665)
    at t.sendMessage (mathlive.min.mjs?module:2264:21180)
    at t.executeCommand (mathlive.min.mjs?module:2264:22864)
    at t.handleMessage (mathlive.min.mjs?module:2264:20215)
    at t.handleEvent (mathlive.min.mjs?module:2264:19665)
    at t.sendMessage (mathlive.min.mjs?module:2264:21180)
    at t.executeCommand (mathlive.min.mjs?module:2264:22864)
```

### Expected Behavior

Quite obviously, I need the virtual-keyboard to work not to trigger an endless event-loop.

### Environment

**MathLive version: latest**

**Operating System: macOS**

**Browser: Chrome**

**Comment by arnog** [comment] 2023-09-17 16:01
When you say "latest" for the version of MathLive, can you be more specific? Is it the version from npm or from the main branch? I have recently attempted to address this issue (see https://github.com/arnog/mathlive/issues/2135), so I'm wondering if you have the fix and the fix doesn't work, or if you don't have the fix.

**Comment by szn** [comment] 2023-09-17 17:54
Thanks @arnog for your prompt reply. The example above uses the latest official npm package (`0.95.5`). But I tried versions `0.95.4`, `0.95.5` and the tip of main with `npm i github:arnog/mathlive`.

Minutes ago I also checked this specific commit hash from #2135 (`npm i github:arnog/mathlive#7e853eb`).

None of the above worked for me.

**Comment by arnog** [comment] 2023-10-11 16:05
This issue is a bit tricky to debug because it requires a specific setup: a main document and an ifram on different hosts, with a mathfield inside the iframe. In this situation, the trick is to detect that the iframe and the keyboard are in the same window, even though Cross-Origin protection prevents communication between them. You can have a look at https://github.com/arnog/mathlive/commit/7e853eb7295a7c2179cc997fe8393f56077daa6b to see where I attempted to detect this. The test appears to be insufficient. Since you have an environment where you can reproduce this, maybe you can try to put a breakpoint at this location, and observing the various values of `window`, `window.top`, `window.parent` and perhaps `globalThis`` and others, can determine what the proper test would be.

**Comment by szn** [comment] 2023-10-12 09:15
I did a number of experiments trying to detect an iframe. And I can make it (with `window.self !== window.top` for example). But if only I allow `this.executeCommand(command!);` I have an infinite loop. So I can either have a version works inside an iframe, or outside.

BUT if I ignore the logic and put a `return;` statement that prevents any `this.executeCommand(command!);` execution „everything” works fine. See https://github.com/arnog/mathlive/commit/7e853eb7295a7c2179cc997fe8393f56077daa6b#r129791789

I am sure I am not following the logic here—there has to be a reason for this `executeCommand`.

**Comment by arnog** [comment] 2023-11-16 19:13
I believe a PR related to this has been merged. Please reopen if you still have this issue.

**Closed by arnog** 2023-11-16 19:13 UTC

**Comment by szn** [comment] 2023-11-17 10:57
Yes, I can confirm the fix. Thank you very much @arnog!
