### ISSUE TITLE
Pasting text as text

### ISSUE THREAD

**Issue by jgore077** [arnog/mathlive#2061] opened 2023-07-17 17:11 UTC
## Description

Im in love with the mathlive library, It was super easy to setup and works phenomenally well.

My only issue is that pasting text is very difficult as all pasted text is automatically in LaTex/math mode.

I would like to know the best solution for text pasting.

I had developed a solution that worked but upon further testing the expanded latex forms would cause my
cursor position to be invalidated so I made my way to the repository to seek help.

I also apologize for being somewhat unprofessional with this issue report but Im currently in a internship that only has two weeks left and this is the last piece of the project.

### Expected Behavior
When the user is in mathmode the text should be pasted as is with no alterations.

My previous solution was to wrap text inside a latex text block which looks like this "\\text{}" and the text goes inside the curly braces.

I had to abandon this solution as the expanded LaTeX forms would cause my cursor position to get lost.

### What Can Be Done

If no code can be provided the next best thing would be advice on how to fix this problem

**MathLive version**
Current Version

**Browser** 
I would like the solution/method to work on all browsers

**Comment by arnog** [comment] 2023-07-17 21:31
I’m afraid I don’t understand what the issue is. You are pasting something in a mathfield and are getting something else than what you expect? What do you paste? What do you get? What do you expect?

You said you had a solution. Could you share it?

**Comment by jgore077** [comment] 2023-07-17 21:58
Thank you for responding so soon, To clarify my problem I want to be able to paste text and have it show up as text in the mathfield as if it were generated in text mode. Currently all paste does is create math.

My solution only partially works and involves a paste event. If the user is in text mode the default will be prevented and the clipboards text will be put inside a the curly braces in this string "\\text{}". After that I'll use the position attribute of mathfield element to determine where to insert the string. 

The issue was that things like parentheses would be converted to a LaTeX form thus rendering my position invalid as the strings actual representation had changed.

**Comment by arnog** [comment] 2023-07-17 22:07
ok, so if you have "3.1415" on the clipboard, you want to paste it into the mathfield as "\text{3.1415}"? Do you use a regular paste command or do you have a special "Paste As Text" command?

Could you share the actual code you use rather than describing it?

I don't understand the issue with parentheses you're talking about. Or what "my position invalid" means. Again, an actual example and some actual code would be really helpful in understanding the problem you're trying to solve.

**Comment by jgore077** [comment] 2023-07-17 22:38
You are correct about what I'm trying to achieve in the first paragraph

 This is a codepen which includes the entire issue I mentioned. [https://codepen.io/Jimmy-Gore/pen/VwVmzVV](url)

To produce an error paste something into the math-field and then press the T button and enter "()" then  press the T button and copypaste something again.

"()"-> "\rparen\lparen"  which means that it breaks the position I was supposed to insert the string at, causes the string to get split.

Ideally you can point me to how pasting is done in the mathlive.js file so I can deal with it there instead of a external solution.

**Comment by arnog** [comment] 2023-07-17 23:27
Thank you for sharing the code. It is so much easier to debug code when you can actually see it.

To achieve what you want you can simplify your event listener like so:

```js
mf.addEventListener("paste", (e) => {
    if(!mathmode) return;
    
    mf.insert(`\\text{${e.clipboardData.getData('text')}}`)
    e.preventDefault()
 });
```

The key is the function `insert()` which will insert the desired content at the current position and handle any adjustment to the position that may be necessary. The `insert()` function has [various options](https://cortexjs.io/docs/mathlive/#(MathfieldElement%3Aclass).(insert%3Ainstance)) which can be used to control how the insertion is done.

**Comment by jgore077** [comment] 2023-07-18 00:50
Thank you so much for the help and thanks even more for making this library!

**Comment by arnog** [comment] 2023-07-18 01:13
Thanks for your kind words!

**Comment by jgore077** [comment] 2023-07-18 01:51
I have another question that is simpler than the previous one I asked, Do you mind if I ask it here or should I open a new issue?

**Comment by arnog** [comment] 2023-07-18 02:51
Ask away...

**Comment by arnog** [comment] 2023-07-18 17:25
That's because the `defaultMode` (the mode used when the mathfield is empty) is `"math"` by default. You can also change the current mode with `mf.mode`

**Comment by jgore077** [comment] 2023-07-18 18:53
How would I set the default mode?

**Comment by jgore077** [comment] 2023-07-18 22:35
It didnt seem to work, Ive updated my codepen also to demonstrate.
[https://codepen.io/Jimmy-Gore/pen/VwVmzVV](url)

**Comment by arnog** [comment] 2023-07-20 17:47
Fixed in https://github.com/arnog/mathlive/commit/d2625ede31cc6d16f872539c9b37f30ccd3a6466

**Closed by arnog** 2023-07-20 17:47 UTC

**Comment by jgore077** [comment] 2023-07-20 18:33
How should I pull this new code into my project to use it?
