### ISSUE TITLE
No update of value when editing the inside of Dirac braket

### ISSUE THREAD

**Issue by MizarZh** [arnog/mathlive#2488] opened 2024-08-15 09:38 UTC
## Description

No update of value when editing the inside of Dirac braket.

### Steps to Reproduce

1. Type in `\ket`.
2. Use arrow to move cursor inside `\ket`.
3. Type in some values. The value never updates.

![braket](https://github.com/user-attachments/assets/b8994678-4520-4e4c-b696-d6c97badacbd)

This works for `\ket, \bra, \braket, \Ket, \Bra, \Braket`.

### Actual Behavior

No update of value despite the change of the display of the element.

### Expected Behavior

Value and display should be the same.

### Environment

**MathLive version**  _0.100.0_

**Operating System** _Windows_

**Browser** _Chrome, Edge, Firefox_

**Comment by arnog** [comment] 2024-08-15 14:39
This is a duplicate of https://github.com/arnog/mathlive/issues/1565

**Closed** 2024-08-15 14:39 UTC
Labels: duplicate
