### ISSUE TITLE
Feature discussion: select placeholder when moving into it

### ISSUE THREAD

**Issue by ChillingVan** [arnog/mathlive#369] opened 2020-02-06 01:54 UTC
### Current Behavior
Currently, when using ← or → or "movePreviousChar" or "moveNextChar"，and when the cursor is going to a placeholder, the caret will locate to the left or to the right of the placeholder. Whether to the left or the right of the placeholder, the meaning are the same.
![图片](https://user-images.githubusercontent.com/7666419/73899151-af4cec80-48c6-11ea-89e2-6b1ea08069a4.png)

![图片](https://user-images.githubusercontent.com/7666419/73898968-13bb7c00-48c6-11ea-8229-b102f7119b84.png)

### Suggest behavior
When moving into the placeholder, it will automatically select the placeholder. And when moving out of the placeholder, it will leave the placeholder instead of locating to the left or right of it. 
With this, no need to click twice to move out of the placeholder.

**Comment by ChillingVan** [comment] 2020-02-06 01:56
Here is the solution PR:
https://github.com/arnog/mathlive/pull/370

**Comment by arnog** [comment] 2020-02-06 15:18
This is not completely unreasonable. After all, single clicking on the placeholder selects it.

Also, actually selecting the placeholder when navigating with the keyboard makes it explicit that the next insertion will result in the replacement of the placeholder.

It is however a bit odd that a navigation command (→) would cause a selection to happen. Maybe that's OK.

**Comment by ChillingVan** [comment] 2020-02-07 01:39
Yeah, selecting it is not quite good. A better solution is move the caret in the rect of the placeholder. I will close this.

**Comment by arnog** [comment] 2020-02-07 02:19
I don't think you should close this. I think this is an interesting idea that merits discussion and further thought. If you have some ideas on how to further improve it, I suggest you keep this issue open and continue the discussion in this issue.

**Comment by ChillingVan** [comment] 2020-02-07 02:36
Maybe the idea in Microsoft Math is a good example:
![图片](https://user-images.githubusercontent.com/7666419/73996016-6748cb00-4995-11ea-90a9-fdeb3b2a4cf3.png)
Put the caret in the placeholder.
But this seems to not be a easy job to implement. This affect the placeholder layout, render and the caret render...

**Comment by NSoiffer** [comment] 2020-02-07 07:06
I'm in favor of selecting the placeholder. Not too surprising since I lobbied for the placeholder being selected when you click on it ;-)

Placeholders are special in their behavior and I don't think selecting them when you arrow to them is a significant issue because they aren't really there in some sense (they magically disappear when you type next to them). Since they aren't really there, how can you be on the left or right side of them? Also, the behavior of being replaced when you type is consistent with the notion of them being selected and it mirrors the behavior that clicking to the left or right of them selects them.

**Comment by ChillingVan** [comment] 2020-02-18 07:57
A detail may need to be noticed:
If the placeholder is selected when move into its left or right, then entering "delele" or "backspace" will delete the placeholder instead of the content at the left or right of it.

**Comment by OrkhanAlikhanov** [comment] 2020-03-10 19:42
I think instead of allowing putting caret to the left or right of the placeholder, the placeholder should be removed when the cursor/caret is right next to it and added back when caret moves out of it. The latter is already the current behavior, when there is no placeholder it's added as soon as caret moves out of it giving a nice indication that something should be there. 

Here is what I mean by removing the placeholder when the caret is next to it and adding it back. MathQuill is doing that, and I like it: 
<img src="https://user-images.githubusercontent.com/15037839/76351726-62c25a00-6327-11ea-884a-abb7a75b4563.gif" width="100px">

Above clip is from MathQuill's website but I tweaked the css to add placeholder box there, by default they just give some background color to the empty placeholder node. Here is the tweaked css if someone is curious to try: 
```css
.mq-empty::after {
  visibility: visible !important;
  content: '⬚' !important;
}

.mq-empty {
  background-color: transparent !important;
}
```

**Comment by arnog** [comment] 2020-03-10 21:18
@OrkhanAlikhanov Hmmm... I like it.

**Comment by stefnotch** [comment] 2020-09-22 18:55
OrkhanAlikhanov's suggestion of deleting/hiding the placeholder when moving the cursor into them sounds great. Since I quite frequently use placeholders in my application, I'd love to contribute a PR for this.

Any pointers regarding where to get started?

**Comment by arnog** [comment] 2020-09-27 12:38
I think this would require modifying `toMarkup()` in `span.ts`. Specifically, not adding the `ML__placeholder` class when `this.caret` is not undefined. There might be other changes needed, but that's a good start, I think.

**Comment by arnog** [comment] 2020-10-19 08:36
I am currently making some changes to the way selection works that might impact how to resolve this issue. Ask before working on a PR.

**Comment by stefnotch** [comment] 2020-10-19 08:49
Ok, thanks for the heads up! I have some ideas regarding how to implement it, but I'll wait before doing so then.

**Comment by arnog** [comment] 2020-11-10 14:57
The behavior has changed with bcb807d: the placeholders are now automatically selected. Not sure if you want to experiment with further changes, but keep this open in case you do.

**Comment by stefnotch** [comment] 2021-05-09 08:59
Okay, I quite like the current behaviour, although there is still one thing that I find odd. When positioning the cursor after an empty fraction that only has placeholders, the fraction will be 'skipped'. 

`$$3\frac{\placeholder{}}{\placeholder{}}3$$`
![2021-05-09-0150](https://user-images.githubusercontent.com/10220080/117566197-8d3bae80-b0b5-11eb-9029-cc2d62581204.gif)

**Comment by arnog** [comment] 2021-05-09 14:11
I don’t understand what you mean. What I see in the screencast:
- you place the caret before the fraction
- you navigate (by pressing the right arrow?)
- -> the numerator placeholder is selected, then the denominator, then you end up after the fraction

I don’t understand what was “skipped” or what you expected to happen. Could you expand a bit?

**Comment by stefnotch** [comment] 2021-05-09 15:42
Oh, I should have described it a bit more clearly. It really isn't obvious from the video.
So, what is happening is the following
- I place the caret before the fraction
- I navigate using the right arrow (selects numerator and denominator)
- Then the caret is after the fraction
- And finally, I attempt to navigate using the *left* arrow (skips over the fraction)

**Comment by arnog** [comment] 2021-05-09 19:01
Ah, OK, got it.
I can't reproduce it with 0.64 and I might have fixed it. Could you give it another try and let me know if you still see it with 0.64?

**Comment by stefnotch** [comment] 2021-05-09 19:38
Oh sweet, it is indeed fixed with 0.64. 🥳

**Comment by stefnotch** [comment] 2021-05-10 06:14
I suppose this issue could be closed now?

**Comment by arnog** [comment] 2021-05-10 11:34
Yes, I think that's fine. We can always open a new issue for possible improvements over the current behavior.

**Closed by arnog** 2021-05-10 11:34 UTC
Labels: feature
