### ISSUE TITLE
edited values in self-defined function are not showing in latex

### ISSUE THREAD

**Issue by svitrol** [arnog/mathlive#2120] opened 2023-08-31 11:04 UTC
Fairly new to mathlive.
I was going about defining new symbol by this guide:
https://cortexjs.io/compute-engine/guides/augmenting/
But I wanted to edit the values in the newly defined function so I went to macros:
https://cortexjs.io/mathlive/guides/macros/

![obrazek](https://github.com/arnog/mathlive/assets/57999718/dd4e9971-b703-4c48-ad59-39adea7c6c40)

and set` captureSelection: true`
but that did not work. The logic is inverted so even in the playground. `captureSelection: false` does work and now I can edit the values in the function.

The problem is that when I edit the values in the function in Mathfield and then read 
`mfe.value` the latex content does not refresh. 

![obrazek](https://github.com/arnog/mathlive/assets/57999718/66b775e0-a60a-4fdd-a44b-85d6d65915c5)
after writing current value to console
![obrazek](https://github.com/arnog/mathlive/assets/57999718/e9102133-a3c7-4a3c-9dc6-b8eb4b3589f4)

Is there another property that has the current content?
I tried to listen to input and write to console the value with every change, but the event was triggering and the value was not changing.

macro defined:
`funfunction: {
            captureSelection: false,
            args: 2,
            def: 'FunFunction\\left({#1},{#2}\right)',
        }` 
function inserted into mathfield by button
`mfe.executeCommand(['insert', '\\funfunction{1}{1}'])`

mathlive version: 
`"mathlive": "^0.95.0"`

**Comment by svitrol** [comment] 2023-08-31 19:09
well yes it is not mfe.value but the json made from it, 
![ezgif com-crop](https://github.com/arnog/mathlive/assets/57999718/3b667490-56d6-4e14-b2e5-4a8f43970d3e)
but this gif shows my situation much better hope it helps in replicating the issue.

But if you have an idea what type of setting I should check. Was stuck on this for a few hours and didn't find what is wrong.

**Comment by arnog** [comment] 2023-08-31 20:21
Could you share your code? What happens when you click on the "Get MatjJson" button?

**Comment by svitrol** [comment] 2023-09-01 04:33
well that is just a bunch of log commands.
`getFunctionMathJson() {
        console.log('H');
        console.log(this.mfe3.value);
        const mathJson = this.computeEngine.parse(this.mfe3.value).json;
        console.log(mathJson);
        console.log(this.mfe3.getValue('math-json'));
        return mathJson;
    }`

![obrazek](https://github.com/arnog/mathlive/assets/57999718/b35181b3-5103-4659-95e6-70703e80b82c)

**Comment by svitrol** [comment] 2023-09-01 11:42
Tried to create some minimal version that would work and change the values in latex but for now still nothing.
Here is the minimal project:
https://github.com/svitrol/mathlive-test/tree/master

ng version: 
Angular CLI: 16.1.8
Node: 18.14.0
Package Manager: npm 6.14.15
OS: win32 x64

**Comment by arnog** [comment] 2023-09-01 14:53
I tried to run the project, but I get an error when trying `npm install`:

`Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"`

Could you describe the problem you are seeing with the example you gave? Is it that after you invoke `executeCommand()` the `input` event is not dispatched? Or something else? What steps should I follow to reproduce the problem?

**Comment by svitrol** [comment] 2023-09-01 16:07
_Is it that after you invoke executeCommand() the input event is not dispatched?_
The event triggers but the value stays the same no matter what I write inside the function's brackets.
If I have cursor inside the brackets and insert another function that changes the mfe.value, but nothing else seems to change the value inside the brackets.

But when I write something outside the function, the mfe.value changes and every other function that is not mine works fine as well.

**Comment by svitrol** [comment] 2023-09-01 17:10
_I tried to run the project, but I get an error when trying npm install:
Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"_
Committed new version now it should be alright. 
Did from a pc that does not have _auth in my ~/.npmrc. Hope you can now replicate my issue.

**Comment by arnog** [comment] 2023-09-01 17:12
ok, thanks. I can now replicate the issue.

**Comment by rs-mobitech** [comment] 2023-09-02 13:11
I tried the same and noticed something else.  When I move back into the function parenthesis and enter a number, it does not appear after the 1, and there is a space between the 1 and the number. 

<img width="716" alt="Screenshot 2023-09-02 at 21 06 57" src="https://github.com/arnog/mathlive/assets/39233783/bf292dc3-a248-4bc9-9b74-c784ca57355a">

**Comment by arnog** [comment] 2023-09-03 22:59
(Note: this is related to #1565)

**Comment by svitrol** [comment] 2023-09-04 13:53
Right so redefined macros with expand: true and use .getValue('latex-expanded'). I got output `\funfunction\left({15},{16}\right)`.
If I give this in to the compute engine to parse I get error. Turns out I have to remove `\left(,\right)`. So i defined custom symbols for braces and comma so that when I remove them I get only those around my custom functions. 
But this way not always works sometimes I click somewhere on the param of the function but it writes outside of the curly braces in the latex.
So any other way or how to make it better?
Thanks for the advice at least now I can get the output json.

**Comment by arnog** [comment] 2023-09-04 15:26
@svitrol could you share the macro definition you are using? Note that you don't need braces around the argument. They shouldn't hurt, but they're not needed.

**Comment by svitrol** [comment] 2023-09-04 17:05
Already committed new version. The macro looks like this:
```'coolseparotor': {
                args: 0,
                def: ',',
                captureSelection: false,
                expand: false,
            },
             'leftbrace': {
                args: 0,
                def: '',
                captureSelection: false,
                expand: false,
            },
 'rightbrace': {
                args: 0,
                def: '',
                captureSelection: false,
                expand: false,
            },
'funchelpsymfunfunction': {
            args: 0,
            def: 'FunFunction',
            expand: false,
        },
'funfunction': {
            captureSelection: false,
            args: 2,
            def: '\\funchelpsymfunfunction\\leftbrace\\left({#1}{#2}\\rightbrace\\right)',
            expand: true,
        }```

I got two definitions for a function one only as a function name so that it acts as one symbol and the second definition for arguments so it can be editable and can be expanded.
after  .getValue('latex-expanded')
use function
```function removeHelpSymbols(latex: string): string {  
    let resultLatex = latex;  
    resultLatex = resultLatex.replaceAll('\\rightbrace\\right)', '');  
    resultLatex = resultLatex.replaceAll('\\leftbrace\\left(', '');  
    resultLatex = resultLatex.replaceAll('\\coolseparotor', '');  
    resultLatex = resultLatex.replaceAll('funchelpsym', '');  
    return resultLatex;  
}```

I need the curly braces to know where each arg starts and ends and the parentheses for the symbolism that it is a function.

**Comment by svitrol** [comment] 2023-09-08 08:33
Is there a way to make it so that when user moves a cursor it can ignore some latex commands? So that user does not delete the curly braces  and break the formula? Like lock some parts of the formula so user can still edit just not some parts. Like I would like the user to be able to fill args of a function but not be able to remove separators? and when user is trying to remove a function it removes whole function not by parts?

**Comment by svitrol** [comment] 2023-09-08 11:20
![ezgif com-crop](https://github.com/arnog/mathlive/assets/57999718/e137632f-c50f-4d99-86e9-18ae0ca3819d)
Here this gif demonstrates what happens when I insert function and replace placeholders by numbers, but when I try and navigate there with arrows I am unable to. In the gif above I was pressing number 1 and arrow right alternatively. I managed to write 1 to places I don't want the user to edit but not in the places the user should be able to edit.

**Comment by arnog** [comment] 2023-12-08 23:00
Dupe of #1565

**Closed by arnog** 2023-12-08 23:00 UTC
Labels: duplicate
