### ISSUE TITLE
Auto generate when write equation

### ISSUE THREAD

**Issue by buingocdu** [arnog/mathlive#1257] opened 2021-12-03 02:49 UTC
Can you try input:
a\ne k\pi\Rightarrow \sin a \ne 0
(this is latex. you can paste. then input by image)
character is automatically generated but it is wrong.
thanks!

**Comment by arnog** [comment] 2021-12-03 04:21
Is this a duplicate of #1222 or is there some other issue?

**Comment by arnog** [comment] 2022-04-13 04:49
Closing  as duplicate

**Closed by arnog** 2022-04-13 04:49 UTC
Labels: duplicate
