### ISSUE TITLE
\ne ,\neq and \not= are not working.

### ISSUE THREAD

**Issue by faxinwang** [arnog/mathlive#1024] opened 2021-06-19 12:46 UTC
## Description

\ne ,\neq and \not= are not working. 

input: A\ne B
output: AB
expected:A\ne B

input: A\neq B
output: AB
expected: A\neq B

input A\not=B
output: A=B
expected:A\not= B

Note that the editor dispalying the right content, only the output latex value is not as expected.

### Environment

**MathLive version** 0.69.3

**Operating System** [Windows 10]

**Browser** [ Chrome]

**Comment by stefnotch** [comment] 2021-06-22 10:07
Additional Info:
If one types `A \ne B`, the copied MathJson ends up being: `["Multiply","A","B"]`. This seems to be related to the issue

**Comment by arnog** [comment] 2021-06-22 10:25
Ah, yes, that's probably the problem...

**Comment by faxinwang** [comment] 2021-06-22 14:15
Do you mean I just need to upgrade mathlive to 0.69.4 ?

I have upgraded to 0.69.4, but the problem still exists.

**Comment by faxinwang** [comment] 2021-09-19 14:16
Hi, is there any progress on this problem? I have tried typing A \ne B on this page(https://cortexjs.io/mathlive/demo/), the output is still AB。

**Comment by arnog** [comment] 2022-04-13 23:40
I believe this was a duplicate of #1222, which is now fixed.

**Closed by arnog** 2022-04-13 23:40 UTC
Labels: bug
