### ISSUE TITLE
[math-field] Boolean properties (smart-mode, smart-fence, etc) not taking effect

### ISSUE THREAD

**Issue by harinair-1** [arnog/mathlive#1068] opened 2021-07-04 06:31 UTC
## Description

`smart-fence` `smart-mode` `smart-superscript` and similar boolean properties are not working when using `<math-field></math-field>`. It works just fine when initializing a mathfield using `new MathfieldElement()`.

I have tried the following:

`<math-field smart-mode="true" virtual-keyboard-mode="manual"></math-field>`
`<math-field smart-mode=true virtual-keyboard-mode="manual"></math-field>`
`<math-field smart-mode="on" virtual-keyboard-mode="manual"></math-field>`
`<math-field :smart-mode="true" virtual-keyboard-mode="manual"></math-field>`

The SDK documentation mentions that it should be 'true' or 'false', not sure if I am missing something.

Thanks!

### Environment

**MathLive version**
0.65.0

**VueJS version**
2.6.14

Edit: added in one more scenario I tried.

**Comment by arnog** [comment] 2021-07-04 07:50
This is due to the fact that the default value of those boolean attributes conflict with the actual default value. Duplicate of #1022

**Closed by arnog** 2021-07-04 07:50 UTC
Labels: duplicate

**Comment by harinair-1** [comment] 2021-07-04 08:19
Thanks, understood. So there is no way to get this to work at the moment using the mathfield element is that right?

**Comment by arnog** [comment] 2021-07-04 08:41
No, unfortunately not. You have to use `setOptions()` to modify those attributes.

**Comment by arnog** [comment] 2021-07-04 08:43
No, unfortunately not. You have to use `setOptions()` to modify those attributes.

**Comment by harinair-1** [comment] 2021-07-04 08:48
Thanks, I'll keep an eye on #1022 then.
