### ISSUE TITLE
Wrong position of selection higlights when scaled the parent node of the MathfieldElement 

### ISSUE THREAD

**Issue by kingnare** [arnog/mathlive#1938] opened 2023-04-21 01:11 UTC
## Description

- Open cortexjs.io/mathlive/demo

- Scaled the parent node of the MathfieldElement.
![A](https://github.com/kingnare/kingnare.github.io/raw/master/A.png)

- Input lots of chars, scroll to end
![B](https://github.com/kingnare/kingnare.github.io/raw/master/B.png)

- Select chars "END"
![C](https://github.com/kingnare/kingnare.github.io/raw/master/C.png)

And this is working for me:
Modified function "adjustForScrolling" in mathlive.js:
`const left = Math.ceil(rect.left - fieldRect.left + mathfield.field.scrollLeft * scaleFactor);`

"scaleFactor" is from function"renderSelection"

**MathLive version**
0.92.1

**Operating System** 
Windows 10

**Browser** 
Chrome latest

**Comment by arnog** [comment] 2023-04-21 01:17
That's a duplicate of #1939, right?

**Comment by kingnare** [comment] 2023-04-23 00:13
Sorry. I've made a mistake  :)

**Comment by arnog** [comment] 2023-04-23 01:10
No worries.

**Closed by arnog** 2023-04-23 01:10 UTC
Labels: duplicate
