### ISSUE TITLE
[bug]: attempting to render latex symbol `\iff` causes infinite recursion

### ISSUE THREAD

**Issue by michaelhthomas** [arnog/mathlive#2271] opened 2024-01-23 20:44 UTC
## Description

> (Optional) Provide a brief summary of the issue.

The `\iff` symbol causes the LaTeX renderer to infinitely recurse.

### Steps to Reproduce

> (Required) Provide steps that are specific and repeatable

**CodeSandbox**: https://26v59c.csb.app/

1. Create a MathLive input field
2. Attempt to input `\iff`

### Actual Behavior

> (Required) What happened when you followed the steps above?

The LaTeX renderer infinitely recursed, causing script execution to be halted and breaking the editor. Below is the exact text of the browser error:

```error
Uncaught InternalError: too much recursion
    An https://unpkg.com/mathlive:193
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
    scan https://unpkg.com/mathlive:2804
    oe https://unpkg.com/mathlive:2804
    scanMacro https://unpkg.com/mathlive:2804
    scanSymbolOrCommand https://unpkg.com/mathlive:2804
    scanSymbolCommandOrLiteral https://unpkg.com/mathlive:2804
    parseExpression https://unpkg.com/mathlive:2804
mathlive:193:4387
```

### Expected Behavior

> (Required) What did you expect to happen instead? It may be obvious to you what should have happened, but if you don't state it explicitly it may not be obvious to others.

The symbol should be rendered correctly; the renderer should not infinitely recurse.

### Environment

> Is this a regression: did it use to work in a previous version?

I have only attempted this using the latest version of MathLive, so unsure if it's a regression.

**MathLive version**:  0.98.5

**Operating System**: macOS 14

**Browser**: Firefox; Chrome

**Comment by arnog** [comment] 2024-01-23 21:41
Looks like a duplicate of #2237

**Comment by michaelhthomas** [comment] 2024-01-23 21:42
Oops, that one didn't come up when I searched. It is indeed a duplicate.

**Closed** 2024-01-23 21:42 UTC
Labels: duplicate
