### ISSUE TITLE
Support RTL and bidirectionality

### ISSUE THREAD

**Issue by zeyad-ahmad-aql** [arnog/mathlive#1696] opened 2022-11-01 09:36 UTC
## Description

This is a feature request. I want to use the mathlive with RTL characters, Arabic for example. If possible, Can you implement the bahvior for RTL support in displaying the math-field and traversing it.

**Comment by zeyad-ahmad-aql** [comment] 2022-11-21 13:33
Hi @arnog, I was wondering if you can kindly provide me with your thoughts about this.

**Comment by arnog** [comment] 2022-11-21 19:14
Sorry for the delay, I somehow missed this issue.

This is a duplicate of https://github.com/arnog/mathlive/issues/686

The summary is that this would definitely be an interesting feature, but it represents a lot of work. It would also require a good understanding of Arabic mathematic notation, and I'm not sure I have the necessary expertise.

However, if someone with the interest and expertise were interested in contributing to the project, I'd be more than happy to consider merging it to the main branch.

**Closed** 2023-01-19 01:52 UTC
Labels: duplicate
