### ISSUE TITLE
> Hi Arnog, thanks for replying. sorry for being so vague.

### ISSUE THREAD

**Issue by abinaya92s** [arnog/mathlive#1254] opened 2021-11-28 16:39 UTC
> Hi Arnog, thanks for replying. sorry for being so vague.
> 
> This is my Angular versions
> 
> ![Screen Shot 2021-11-28 at 10 09 50 AM](https://user-images.githubusercontent.com/95161574/143773931-cf104d9e-0839-47ed-b5f3-f6f016bc67ba.png)
> 
> I have included mathlive.js, mathlive.min.js from node_modules in angular.json file.
> 
> I am also getting the following console error
> 
> ![Screen Shot 2021-11-28 at 11 28 50 AM](https://user-images.githubusercontent.com/95161574/143777072-53a2fda5-c9f6-4f63-b7c4-9f42474781e9.png)
> 
> Please help me use Mathlive virtual keyboard

@arnog

_Originally posted by @abinaya92s in https://github.com/arnog/mathlive/issues/1253#issuecomment-981114116_

**Comment by arnog** [comment] 2021-11-28 18:45
Dupe of #1253

**Closed by arnog** 2021-11-28 18:45 UTC
