### ISSUE TITLE
Mathlive command "applyStyle" color does not persist in state. 

### ISSUE THREAD

**Issue by huzailhassan** [arnog/mathlive#1608] opened 2022-09-04 16:18 UTC
When changing the text color of the math text , for example, from the virtual keyboard, the method "applyStyle" is used. The problem here is that the command uses latex "\mathcolor{}{}" instead of "\textcolor{}{}" when changing the color using this command. We have a situation where we are persisting the state on refresh, and "\mathcolor{}{}" does not persist and changes into regular latex. 

Before Refresh:
![image](https://user-images.githubusercontent.com/61159990/188323030-faf5f1d1-414e-47f6-a187-d0b4210480b4.png)
Latex: "\mathcolor{red}{thisistext}"

After Refresh:
![image](https://user-images.githubusercontent.com/61159990/188323036-4e9df37b-3a20-48de-ae74-593198a7336b.png)

An observation I have made is that "textcolor{}{}" WILL persist on refresh and will not turn into regular latex. "\textcolor{}{}" is the correct latex command and now I am trying to figure out how can I replace "\mathcolor{}{}" with "\textcolor{}{}" on the virtual keyboard as we are unable to ship our product until we figure out a way to replace the button, as to not cause problems for our users.

Mathlive version: "mathlive": "^0.77.0"

Thank you

**Comment by arnog** [comment] 2022-09-04 17:58
This is a duplicate of #1592

**Closed by arnog** 2022-09-04 17:58 UTC
Labels: duplicate
