### ISSUE TITLE
 The focus of the input is lost when typing quickly.

### ISSUE THREAD

**Issue by eliu-fracta** [arnog/mathlive#2182] opened 2023-11-23 10:10 UTC
## Description

https://github.com/arnog/mathlive/assets/109644973/16aab2ca-7db4-4720-ac1e-5082de614ed6

 [codesanbox](https://codesandbox.io/p/devbox/old-tdd-rwgxft?file=%2Fcomponent%2FMathInput.js%3A5%2C35&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpb03g4c00092v6ipzrh33ol%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpb03g4c00032v6ie3hhlsz4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpb03g4c00062v6i1du2g3s0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb03g4c00082v6itopo9f7m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpb03g4c00032v6ie3hhlsz4%2522%253A%257B%2522id%2522%253A%2522clpb03g4c00032v6ie3hhlsz4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb0bd6s00032v6i89jdg69m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A35%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A35%257D%255D%252C%2522filepath%2522%253A%2522%252Fcomponent%252FMathInput.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpb0bd6s00032v6i89jdg69m%2522%257D%252C%2522clpb03g4c00082v6itopo9f7m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb03g4c00072v6ivrgzqggh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpb03g4c00082v6itopo9f7m%2522%252C%2522activeTabId%2522%253A%2522clpb03g4c00072v6ivrgzqggh%2522%257D%252C%2522clpb03g4c00062v6i1du2g3s0%2522%253A%257B%2522id%2522%253A%2522clpb03g4c00062v6i1du2g3s0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb03g4c00042v6in4bv7d37%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clpb03g4c00052v6iw0n3pp24%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp1zlxc1000gedjw0kvy7j6h%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpb03g4c00042v6in4bv7d37%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce

type quickly with your mobile browser

### Actual Behavior

the focus of the input will be lost and under the "auto" virtual keyboard setting, the keyboard will disappear as well 

sometime it will show the error below:
![image](https://github.com/arnog/mathlive/assets/109644973/a349e976-f7b9-4d57-9f60-ec6c12241383)

### Expected Behavior

the input of the focus should be kept even if you type quickly

### Environment

**MathLive version**  0.97.2

**Operating System** IOS

**Browser** Safari 

**Framework** Next 14.0.3

**Comment by arnog** [comment] 2023-11-24 02:12
Unfortunately, I am not much of a React expert. From the limited exploration I've done, the problem seems to be that at some point React decides that the DOM needs to be updated, which causes the focus to be removed from the mathfield). I tried adding a `key` prop, but that didn't seem to make a difference. I don't know if this is the intended behavior of React, or if if it is a React bug. I couldn't replicate the problem using the Simulator, and it seems to only happen on physical hardware.

I suggest you try to get some React expect to investigate.

**Comment by edward1127** [comment] 2023-11-24 03:25
thanks for the reply!

**Comment by arnog** [comment] 2023-12-08 23:01
Closing

**Closed by arnog** 2023-12-08 23:01 UTC

**Comment by sunki-hong** [comment] 2024-04-01 15:34
Wondering if there is an estimated timeline for when it might be included in a release? 

Thanks your hard work and dedication to the project!

**Comment by anterb** [comment] 2024-10-07 00:02
@edward1127 Did you find any solutions here? I have the same problem, it's Next 13.3.0 and MathLive 0.101.0.

**Comment by edward1127** [comment] 2024-10-07 03:07
> @edward1127 Did you find any solutions here? I have the same problem, it's Next 13.3.0 and MathLive 0.101.0.
Nope I haven't found any solutions
