### ISSUE TITLE
Issue with concatenation of macros and letters in LaTeX output

### ISSUE THREAD

**Issue by oatymart** [arnog/mathlive#835] opened 2021-02-25 15:00 UTC
## Description

This may be a misconfiguration on my part.

When entering math like `a \times b` or `\pm x`, the rendering is good in the Mathfield. But when I call `.getValue()` (or `.getValue('latex-expanded')`), the string returned looks like `a\timesb` or `\pmx`. And when I use this string later in a static context, a call to `renderMathInElement()` can't make sense of it due to the concatenation.

This is strange because the version running on https://mathlive.io/examples/latex/index.html shows correct LaTeX output `a\times b` including a space. (Although I see that version doesn't show a `<math-field>` element in the DOM; mine does).

I've also tried the option `ignoreSpacebarInMathMode: false` without success.

## Steps to Reproduce

1. Type `a`, `\times`, (`Enter`), `b` into a Mathfield
2. Call `.getValue()` and store the string
3. Render string into an element between tags `$$ $$`
4. Call `renderMathInElement()`

### Actual Behavior
![Screenshot 2021-02-25 at 15 46 39](https://user-images.githubusercontent.com/43652944/109170177-d8b21200-7780-11eb-8ea2-e983ac85e92b.png)

![Screenshot 2021-02-25 at 15 55 53](https://user-images.githubusercontent.com/43652944/109171583-36932980-7782-11eb-8004-17cb34188b93.png)

### Expected Behavior
![Screenshot 2021-02-25 at 15 46 55](https://user-images.githubusercontent.com/43652944/109170123-cd5ee680-7780-11eb-8f67-0be4931fc3be.png)

String value `"a\times b"` or equivalent.

### Environment

**Operating System**
OSX 10.15.6

**Browser**
Chrome 87

**Comment by arnog** [comment] 2021-02-25 15:53
Which version of Mathlive are you using?

I seem to recall there was a bug along those lines, but I can't reproduce it in master.

**Comment by arnog** [comment] 2021-02-25 18:10
Yes, that's on my todo lists. There are a few problems in master that I want to fix first.

**Comment by arnog** [comment] 2021-04-13 08:32
Fixed in mathlive@0.60.0

**Closed by arnog** 2021-04-13 08:32 UTC
Labels: unable to reproduce
