### ISSUE TITLE
Feature request: \xrightarrow \xrightleftharpoons

### ISSUE THREAD

**Issue by quadmachine** [arnog/mathlive#180] opened 2019-04-25 09:11 UTC
In chemistry these symbols are used quite often to describe chemical reactions

`A \xrightarrow[]{} B `

`A \xrightleftharpoons[]{} B `

Here are other examples of extensible arrows
http://ul.authoring.profil-klett.hr/mladen/Supported_Functions__KaTeX_2019-04-25_11-05-12.png

For very short labels, a hacky solution can be used currently, like so
`\overset{\underset{\longrightarrow }{B}}{A}` but it is rarely usable since chemical reactions usually have much longer labels.

I tried implementing this myself, but I am having trouble understanding the inner workings of Tex, any help would be appreciated

**Comment by arnog** [comment] 2019-04-25 19:17
This is essentially a duplicate of #126.
This require implementing support for horizontally stretchy symbols, which can be achieved using a an SVG overlay. This would probably require a modification of the 'overunder' atom type, or a new atom type.

**Comment by arnog** [comment] 2019-04-25 19:29
To clarify, what is currently *not* supported are "extensible" (stretchy) horizontal symbols, with some content above and below them. 

If you only need to do something non-stretchy, like `A \xrightarrow[]{} B`, you can use `A \longrightarrow B` and for `A \xrightleftharpoons[]{} B`, `A  \rightleftharpoons B`

**Comment by quadmachine** [comment] 2019-04-29 07:43
Thanks for the input, I will try to understand `overunder` atom type and extend it to support these features

**Comment by kehsihba-dev** [comment] 2019-09-05 21:44
@quadmachine were you able to implement this?

**Closed** 2020-03-15 00:26 UTC
Labels: Patreon, feature, help wanted
