### ISSUE TITLE
Pasting some LaTeX content not recognized as LaTeX (was: Multiline equations not working)

### ISSUE THREAD

**Issue by Tanzz1058** [arnog/mathlive#1502] opened 2022-06-14 06:32 UTC
## Description

The commands for multiline or gather are not producing expected result.

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Type in any command for gather or multiline equation in latex editor like the one given in documentation.

### Actual Behavior
It gives the following result-
![image](https://user-images.githubusercontent.com/54041822/173508785-e8ed76a1-b7cb-4537-b079-f9f2ca15ccba.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/54041822/173508843-5a2ef6e0-9b29-4208-9852-3cc30273297b.png)

**Comment by arnog** [comment] 2022-06-14 07:04
Hmmm... I could not reproduce this.
Can you provide more details regarding what you typed? While typing, is the LaTeX code displayed in blue and monospaced font?

**Comment by Tanzz1058** [comment] 2022-06-14 07:41
Try this - " \​begin{multline}
    3(a-x) = 3.5x + a - 1 \\
    3a - 3x = 3.5x + a - 1 \\
    a = \frac{13}{4}x - \frac{1}{2}
  \end{multline}"

**Comment by arnog** [comment] 2022-06-14 15:38
It's working fine for me if I type it.

Is the issue that you are trying to paste the text in the field and that it's not recognized as LaTeX then?

**Comment by arnog** [comment] 2022-06-23 22:04
Closing, please comment or reopen if you have any more questions/feedback on this issue.

**Closed by arnog** 2022-06-23 22:04 UTC

**Comment by mklilley** [comment] 2024-10-07 07:22
Hi there @arnog I found where that strange character came from. When I copy the example multline code from the docs at (https://cortexjs.io/mathlive/reference/commands/#other-environments) I get the same problem.

When you look at the dev tools you can see the offending character.

<img width="1463" alt="Screenshot 2024-10-07 at 08 20 42" src="https://github.com/user-attachments/assets/1f1c41c2-fd19-4988-8215-74b98e73e3eb">

I'm happy to fix it if you can point me to where the docs repo lives.

Thanks for creating Mathlive btw, it's just wonderful!

**Comment by arnog** [comment] 2024-10-07 08:34
Ah, that’s good to know. The doc depot is here: https://github.com/cortex-js/cortexjs.io but I suspect this char might get generated by the code higlighter, so that might not be an easy fix.

**Comment by mklilley** [comment] 2024-10-10 08:05
@arnog - Luckily for me, it ended up being an easy fix - yay https://github.com/cortex-js/cortexjs.io/pull/56

**Comment by arnog** [comment] 2024-10-10 09:47
Great! Thanks for the fix.
