### ISSUE TITLE
MathFields interfere with tabbing

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#15] opened 2017-08-31 04:49 UTC
## Description
If you create a page with tabable elements such as buttons, links, or input areas, or elements with 'tabindex' set to a non-negative value, then tabs move you to the next field. However, if you create a MathField (e.g, with MathLive.makeMathField(()), then tabbing gets stuck on the MathField.

## Steps to Reproduce
1.  Edit the location of mathlive in the document below to point to your location.
2.  Open the modified attached file
3.  Press the "tab" key to move to the two input elements -- tabbing works
4.  Remove the "xxx" in the id for the mathfiield, save the file, and reload the page.
5.  Press the "tab" key -- it is stuck in the mathfield.

### Importance
Tabbing is very important for accessibility.

### Environment
Windows 10, both Chrome and Firefox.

### File 
HTML file to try:
```
<!DOCTYPE html><html lang="en-US">
<head>
    <meta charset="utf-8">
    <title>MathLive Sample</title>

    <link rel="stylesheet" href="../mathlive/dist/mathlive.core.css">
    <link rel="stylesheet" href="../mathlive/dist/mathlive.css">
    <script src="../mathlive/dist/mathlive.js"></script>
</head>
<body>
	<input type="text" placeholder="a place to tab to"/>
    <div id='xxxmathfield' style='border: 1px solid #999;padding:5px;'>
        f(x)=
    </div>
	<input type="text" placeholder="another place to tab to"/>
<script>
    const mathfield = MathLive.makeMathField(document.getElementById('mathfield'));
</script>
</body>
</html>
```

**Comment by arnog** [comment] 2017-09-14 21:18
Fixed by implementing focus on adjacent element by default when tabbing out of the mathfield.
To override this behavior, provide a onTabOutOf handler.

**Comment by NSoiffer** [comment] 2018-12-05 20:34
The tabbing fix works well. What is missing from the report, and hence from the solution, is that shift+tab needs to do the symmetric thing (move backward/left) out of the mathfield.

**Comment by arnog** [comment] 2018-12-10 20:49
Could you provide more details as to what is not working? The `onTabOutOf` handler has an argument which is a positive integer when tabbing forward and a negative integer when tabbing backward (shift-tab).

**Comment by arnog** [comment] 2018-12-19 05:01
I can't reproduce the problem. Shift-tab goes backward, as expected. Could you have a keyboard handler that's interfering?

**Closed by arnog** 2018-12-19 05:01 UTC
Labels: benetech
