### ISSUE TITLE
Placeholder editing no longer fires "input" events on parent

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1728] opened 2022-11-25 15:08 UTC
On 0.85.1, I have a readonly math field, with an "input" event listener registered. On 0.84.0, when I typed in any of the placeholders, the input event would fire on the parent. This no longer happens. Is there some other way I should be listening for these changes?

Also, if I make a math-field that is NOT read-only,

- I don't see the placeholder defaults, just the box
- - the first edit I do deletes the `.placeholder` entry in the mathfield.

With readonly: 

<img width="678" alt="image" src="https://user-images.githubusercontent.com/69635/204011860-65a3ebdc-7f19-45c2-b568-b43ad5668f9c.png">

Without readonly:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/69635/204012034-d153c2fe-6a8d-4bee-ab13-9f5e23b8eb9c.png">

You can see this on the demo page too: 

<img width="817" alt="image" src="https://user-images.githubusercontent.com/69635/204012221-91f02c6a-ac27-41bc-9bd3-80d3cdbabc98.png">

Missing placeholders: 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/69635/204012572-eab8d625-3e73-4a1d-8830-5ff53ea1ef68.png">

**Comment by arnog** [comment] 2022-11-27 21:20
Yes, there is a separate change event for placeholders, it's the `placeholder-change` event. It includes a `placeholderId` property so you can tell where the change comes from.

**Comment by arnog** [comment] 2022-11-27 21:21
The rest of the behavior to describe is as intended, I think: placeholders are editable only when place inside a read-only math-field.

**Comment by gerryfletch** [comment] 2022-11-27 23:01
Hm, I'm on the latest and I'm not getting any events for the parent math field element, or any nested (placeholder) math-field elements.

```javascript
const mfe = ...
mfe.addEventListener("input") // fires
mfe.addEventListener("placeholder-change") // doesn't fire
const nested = mfe.shadowRoot?.querySelector("math-field") as HTMLElement;
nested.addEventListener("placeholder-change") // doesn't fire
```

LaTeX used:

```latex
\placeholder[user-answer]{}
```

**Comment by arnog** [comment] 2022-11-28 09:10
Fixed now in the main branch. Note that you need to listen to the `"placeholder-change"` event on the host mathfield.

**Closed by arnog** 2022-11-28 09:10 UTC
Labels: bug
