### ISSUE TITLE
Cannot edit Chemical equations after being rendered

### ISSUE THREAD

**Issue by ImGelu** [arnog/mathlive#1688] opened 2022-10-22 14:36 UTC
## Steps to Reproduce

1. Type a chemical formula, for example `\ce{CaCO3 + H2O}`
2. Press `Enter` so the rendering begins
3. Try to edit the formula. The cursor works only for the begining or the end of the formula.

### Environment

**MathLive version**: Latest (0.84.0)

**Operating System**: Windows 11

**Browser**: Firefox

**Comment by arnog** [comment] 2022-10-22 16:06
Duplicate of #1493

**Closed by arnog** 2022-10-22 16:06 UTC
Labels: duplicate
