### ISSUE TITLE
Math mode produces the incorrect latex

### ISSUE THREAD

**Issue by shareefalis** [arnog/mathlive#2164] opened 2023-10-26 15:06 UTC
## Description

Math live's math mode produces incorrect latex when trying to use the `ctrl+enter` keyboard shortcut
 Here is the latex it produces
```\begin{lines}1\\ 1\end{lines}```

### Steps to Reproduce
In math mode:
1.  type 1
2. ctrl+ enter 
3. enter 1 (produces the expected behavior)
5.  save the latex  
6.  rerender the latex with mathlive ( produces the actual behavior)

### Actual Behavior
<img width="293" alt="Screenshot 2023-10-26 at 10 00 36 AM" src="https://github.com/arnog/mathlive/assets/1189805/504ab6b2-4ad2-4ae6-8ae7-b9839bfb40eb">

### Expected Behavior
<img width="439" alt="Screenshot 2023-10-26 at 9 58 26 AM" src="https://github.com/arnog/mathlive/assets/1189805/fcc6a7d4-7ba5-4aef-81f0-d9a11a49cc9d">

### Environment

> Is this a regression: did it use to work in a previous version?  

i don't know

**MathLive version**  0.95.0

**Operating System**  macOS 13.6

**Browser** Chrome 117

**Comment by arnog** [comment] 2023-12-08 22:58
Dupe of #2000

**Closed by arnog** 2023-12-08 22:58 UTC
Labels: duplicate
