### ISSUE TITLE
Displaying long text with math field

### ISSUE THREAD

**Issue by yethuaungptu** [arnog/mathlive#1162] opened 2021-09-11 09:21 UTC
## Displaying long text

I want to display long text math-field (eg some math exam questions). 
`<math-field>math sign and text </math-field>`
But result display is just show body width.
How to add auto new line when question is overflow of body

**Comment by arnog** [comment] 2023-12-08 23:08
Dupe of #598

**Closed by arnog** 2023-12-08 23:08 UTC
