### ISSUE TITLE
Sums seem to be calculating incorrectly

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2107] opened 2023-08-24 07:43 UTC
When trying your demo I see this:

<img width="223" alt="Screenshot 2023-08-24 at 15 40 25" src="https://github.com/arnog/mathlive/assets/39233783/29a32899-b4b7-42b1-bd4d-8f08b04dd501">

But from what I know the answers should be this:

<img width="840" alt="Screenshot 2023-08-24 at 15 40 12" src="https://github.com/arnog/mathlive/assets/39233783/1e973d03-6af8-4c29-81fe-08a5d36397c1">

Can you help explain why the numeric is giving a number that is one greater.

**Comment by arnog** [comment] 2023-08-24 15:30
Duplicate of https://github.com/cortex-js/compute-engine/issues/93

**Closed by arnog** 2023-08-24 15:30 UTC
