### ISSUE TITLE
[FEATURE] support \mkern command

### ISSUE THREAD

**Issue by zeyad-aql-nagwa** [arnog/mathlive#1355] opened 2022-02-23 08:07 UTC
## Description

mkern spacing commands are not supported. I tried the following latex syntax `\ce{O2 ,Na2CO3 , H2O}` and it pasred it like the following screenshot:

<img width="770" alt="Screen Shot 2022-02-23 at 9 46 09 AM" src="https://user-images.githubusercontent.com/87318803/155279535-89f3a5e8-cb1a-4751-98d5-85dd47e8bdac.png">

First, I investigated a little and thought it was a problem with mhchemParser wrongly parsing the latex, but after that I found out about the mkern spacing commands (I'm still relatively new to latex) and that they're missing from mathlive.

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Open [https://cortexjs.io/mathlive/demo/](https://cortexjs.io/mathlive/demo/)
2. Copy `\ce{O2 ,Na2CO3 , H2O}`
3. Paste it in the latex textarea at the end of the page

### Actual Behavior

The latex is shown like the following:
<img width="445" alt="Screen Shot 2022-02-23 at 10 02 55 AM" src="https://user-images.githubusercontent.com/87318803/155280892-0c83462a-ed22-4c5e-8927-8d0ae2a862a7.png">

### Expected Behavior

For it to be shown like this: 
<img width="257" alt="Screen Shot 2022-02-23 at 10 04 01 AM" src="https://user-images.githubusercontent.com/87318803/155281011-b150a88a-661a-47e9-8ea5-c2047092b9d1.png">

### Environment

**MathLive version: 0.69.9**

**macOS Version 12.2.1 (21D62)**

**Browser: Chrome Version 98.0.4758.102 (Official Build) (arm64)**

**Comment by manstie** [comment] 2022-10-02 03:49
This seems to be fixed? Not occurring on MathLive 0.82 / Windows 10 / Edge + Firefox.

**Comment by arnog** [comment] 2022-10-02 03:56
Ah, yes. Duplicate of #1643

**Closed by arnog** 2022-10-02 03:56 UTC
Labels: feature
