### ISSUE TITLE
v0.69.5 Module parse failed with Webpack

### ISSUE THREAD

**Issue by scorpionknifes** [arnog/mathlive#1135] opened 2021-08-15 09:32 UTC
## Description

Updated from v0.69.4 to v0.69.5 recently and found my Vue v2 and v3 app no longer compiles.

Downgrading back to v0.69.4 fixes the issue.

[If you use Vue, React or some other framework, include a link to a minimal
project demonstrating the issue.]

https://github.com/scorpionknifes/mathlive-bug-issue-webpack-v0.69.5

Sample project using vue v2. (I'm assuming this is also happening on any project using webpack)

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Create vue project using `vue create`
2. `import 'mathlive'`

### Actual Behavior

```
Failed to compile.

./node_modules/mathlive/dist/mathlive.min.mjs 2:2516
Module parse failed: Unexpected token (2:2516)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /* MathLive 0.69.5  */
```

![image](https://user-images.githubusercontent.com/23299540/129473617-0fd0dd7a-e968-456c-b71f-05fdc8e27b5d.png)

### Expected Behavior

Compiles and runs normally

### Environment

**MathLive version** - v0.69.5

**Operating System** - Windows

### Similar?
- https://github.com/arnog/mathlive/issues/938#issuecomment-839570340

**Comment by arnog** [comment] 2021-08-15 10:17
I actually believe it's a duplicate of #1123

**Comment by rexpan** [comment] 2021-08-18 06:36
I use create-react-app 4.0.3 also get error:
```
./node_modules/mathlive/dist/mathlive.min.mjs 167:24
Module parse failed: Unexpected token (167:24)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     const m = (_r$e$trim$match = r[e].trim().match(/^([A-Za-z\d]+)/)) === null || _r$e$trim$match === void 0 ? void 0 : _r$e$trim$match[1],
|           f = m === null || m === void 0 ? void 0 : m.toLowerCase(),
>           g = m ? a[f] ?? a[o[m]] ?? i[m] ?? n[m] ?? t[m] ?? r[e].trim() : r[e].trim();
|     let y = g.match(/^#([\da-f]{2})([\da-f]{2})([\da-f]{2})$/i);
|     if ((_y = y) !== null && _y !== void 0 && _y[1] && y[2] && y[3]) d = Math.max(0, Math.min(255, Number.parseInt(y[1], 16))), u = Math.max(0, Math.min(255, Number.parseInt(y[2], 16))), p = Math.max(0, Math.min(255, Number.parseInt(y[3], 16)));else if (y = g.match(/^#([\da-f]{3})$/i), (_y2 = y) !== null && _y2 !== void 0 && _y2[1]) {
```

**Comment by arnog** [comment] 2021-08-18 07:21
Yes, it appears to be the nullish coalescing operator (`??`) which is causing the problem. WebPack 5 supports it. It appears that react still does not support it. See https://github.com/facebook/create-react-app/issues/9468

**Comment by arnog** [comment] 2022-04-13 23:44
The minified, js,version of the MathLive module is now compiled to be compatible with older toolchains. To use it, make sure to include the `/dist/mathlive.min.js` library.

**Closed by arnog** 2022-04-13 23:44 UTC
Labels: duplicate
