### ISSUE TITLE
Keyboard rendering issue

### ISSUE THREAD

**Issue by zjordan** [arnog/mathlive#906] opened 2021-04-21 16:14 UTC
Recently I have noticed the problem with rendering of the exponent and d/dx symbols on the keyboard - see the picture below. As far as I can tell this issue started just a few days ago and I am not sure what could be the reason.

![image](https://user-images.githubusercontent.com/3768687/115583116-98aa6f80-a297-11eb-9886-7f92bdda67be.png)

In my project I am loading the following scripts:
```
  <link rel="stylesheet" href="https://unpkg.com/mathlive/dist/mathlive-static.css" />
  <script async src="https://unpkg.com/mathlive/dist/mathlive.min.js" />
```
  
 The code that creates a MathfieldElement is as follows:
 
```
    const MathLive = (window as any).MathLive;
    const mfe = new MathLive.MathfieldElement();
    mfe.setOptions({
      virtualKeyboards: "all",
      virtualKeyboardMode: "manual"
    });
```

Browser: Chrome Version 89.0.4389.114 (Official Build) (x86_64)
OS: macOS Big Sur version 11.2.3 

Finally, I do not see the issue when I load the scripts for version 0.59.0:
```
  <link rel="stylesheet" href="https://unpkg.com/mathlive@0.59.0/dist/mathlive-static.css" />
  <script async src="https://unpkg.com/mathlive@0.59.0/dist/mathlive.min.js" />
```

and because of that it looks like the issue started with the version 0.60.0
I would appreciate any insight regarding what could be the source of that problem.

**Comment by arnog** [comment] 2021-04-21 16:42
It is fixed in the main branch.

The issue is that `\exponentialE` and `\differentialD` were declared as macros (they were not in 0.59) and the macros were not loaded to draw the formulas in the keyboard.

**Comment by arnog** [comment] 2021-04-22 15:35
mathlive 0.61 is now available on npm with those changes.

**Closed by arnog** 2021-04-22 15:35 UTC
