### ISSUE TITLE
Can't type 'i' in some cases

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#135] opened 2019-02-11 20:12 UTC
## Description
This is kind of weird, but I can't type an 'i' in some cases

## Steps to Reproduce
1. Open the example in `mathlive/examples/basic/index.html`
2. Click after the `=`
3. Type `pi`

The `p` shows up but now the `i`. If I type another char (.e.,g `x`), it shows up. Typing a second (or third, etc) `i` does nothing, even if I do so after typing `x`.

Similar things happen for the last character of other shortcuts (e.g., `alpha`), although in some cases, typing backspace allows me to enter the char.

**Comment by arnog** [comment] 2019-02-11 22:39
Duplicate of more general #138

**Closed by arnog** 2019-02-11 22:39 UTC
Labels: benetech, bug, duplicate
