### ISSUE TITLE
Shortcuts breaking virtual keyboard functionality

### ISSUE THREAD

**Issue by likeadeckofcards** [arnog/mathlive#817] opened 2021-02-03 20:22 UTC
## Description
If a user tries to enter something like 30cm^2, it causes some problems when using the virtual keyboard.

https://user-images.githubusercontent.com/6399755/106804035-e4536280-6632-11eb-863e-81f17489c7a4.mov

## Steps to Reproduce

1. Enter 30cm using a regular keyboard
2. Open the virtual keyboard
3. Click the x^2 keycap

### Actual Behavior

The latex does not update.

### Expected Behavior

I would expect it to update the latex to either `30\operatorname{cm}^2` or `30\operatorname{cm^2}`

### Environment

Reproducible with the demo tool: https://mathlive.io/examples/latex/index.html

**Operating System**
MacOS

**Browser**
tested both Chrome and Firefox

**Comment by likeadeckofcards** [comment] 2021-02-03 20:25
Also, note that manually entering `30\operatorname{cm}^2` causes the exponent to pushed further away from the characters similar to #203.

**Comment by arnog** [comment] 2021-02-05 12:52
The issue as reported is not reproducible in the main branch, however, the problem of the offset of the exponent still does (this is caused by the exponent being sometimes attached to the `operator` atom, sometimes to a `msupsub`. It should always be a `msupsub`)

**Comment by arnog** [comment] 2021-04-13 08:42
This is now fixed in mathlive@0.0.60

**Closed by arnog** 2021-04-13 08:42 UTC
Labels: bug

**Comment by Smef** [comment] 2021-06-29 19:54
I'm currently using 0.69.4 and this appears to still be an issue, including on the demo site

**Comment by arnog** [comment] 2021-06-29 20:49
@Smef what do you mean by "the demo site"? What URL are you using?

**Comment by Smef** [comment] 2021-07-01 14:31
The same URL as posted in the original issue posting:

https://mathlive.io/examples/latex/index.html

**Comment by arnog** [comment] 2021-07-01 20:10
Ok, this URL was using a version of MathLive that did not have the fix, 

if you’re sure you’re using the latest version and it still happens, I’ll reopen the bug and investigate. You can check the version you’re using with `console.log(MathLive.version)` or by importing `version` from the MathLive module.

**Comment by Smef** [comment] 2021-07-03 02:41
I was incorrect and the newer packaged hadn't been properly installed. My mistake. Thanks for your attention to this issue!

**Comment by arnog** [comment] 2021-07-03 06:03
OK, that's great to hear. Thanks for the update!
