### ISSUE TITLE
The output of auto generated closing bracket is '?'

### ISSUE THREAD

**Issue by moh1434** [arnog/mathlive#836] opened 2021-02-26 20:15 UTC
## Description

The output of auto generated closing bracket is '?'

## Steps to Reproduce

1- Open [mathlive.io](https://mathlive.io/)
2- Write: `(x`, you will see `(x)`
3- Click `Ctrl+A` then `Ctrl+C` (to copy the output)

### Actual Behavior

The output is `$$(x?$$` instead of `$$(x)$$` ,so there is '?' instead of ')'
same behavior with `[x`,`{x`

### Expected Behavior

I expected to get ')' instead of '?'

### Environment

**Operating System**
Linux mint 20

**Browser** 
 Chrome and Firefox

**Comment by arnog** [comment] 2021-02-26 20:52
Right now, that's the intended behavior. Since the closing fence has only been suggested (you can see it's displayed with a lower opacity) and not validated by the user, the Latex representation reflect that.

I can see that what you're expecting is reasonable as well, though... Wondering if anyone else has some thoughts about this?

**Comment by moh1434** [comment] 2021-03-02 14:40
Thank you for your response. I think the output of the suggested bracket should be either empty '' or the right symbol ')'. The '?' symbol is weird and made me think there is something wrong.

**Comment by OrkhanAlikhanov** [comment] 2021-03-07 01:37
I noticed this as well. I really liked the way mathquill works with this to be honest.

**Comment by faxinwang** [comment] 2021-06-19 10:16
I also get Confused by this behavior, I thought the right parentheses was generated automatically, which is the expected behavior for every programmer.

**Comment by arnog** [comment] 2023-03-01 06:01
Fixed now.

**Closed by arnog** 2023-03-01 06:01 UTC
Labels: not a bug
