### ISSUE TITLE
MathfieldElement is not a constructor

### ISSUE THREAD

**Issue by AllyMarthaJ** [arnog/mathlive#1833] opened 2023-02-16 23:40 UTC
## Description

Hi there!

From version 0.87.1+ of MathLive onwards, I'm receiving the error "MathfieldElement is not a constructor".

The code I'm working in uses `require` under the hood with a much older version of webpack, which means that we're using the `mathlive.min.js`. Between 0.86.0 and 0.87.1, esmodule exports seem to have disappeared entirely from the minified JS, but not the mjs file or the full JS. The structure of package.json also seems to have changed, but I don't think that's an issue.

## Steps to Reproduce

The simplest snippet I can think of to reproduce this behaviour is the following:

```
export function App() {
	return (
		<div
			ref={(el) => {
				const mathlive = require("mathlive");
				el?.appendChild(new mathlive.MathfieldElement());
			}}
		></div>
	);
}
```

Changing it to import works as expected.

### Actual Behavior

The code successfully compiles, but doesn't run in browser and throws the error `Uncaught TypeError: mathlive.MathfieldElement is not a constructor`.

### Expected Behavior

Should successfully require MathLive as normal.

### Environment

**MathLive version**
0.89.1

**Operating System** [macOS, Windows, iOS. Include the version]
macOS Ventura 13.2.1

**Browser** 
Chrome 109.0.5414.119
Firefox 109.0.1

Thank you so much for MathLive, it is an amazing project :)

**Comment by arnog** [comment] 2023-02-17 03:46
`mathlive.min.js` is really intended to be used in the browser (i.e. via a `<script>` tag).

The issue is that the `mathlive.min.js` library is packaged as an IIFE. It used to be packaged as a UMD (which also worked with `require()`) but MathLive has updated to the esbuild bundler, which doesn't support the UMD format (https://github.com/evanw/esbuild/issues/507).

Do you really need to use `require()` or could you use `import`?

**Comment by AllyMarthaJ** [comment] 2023-02-17 03:48
Dang. 

Unfortunately the codebase I'm in, every `import` is turned into a `require.ensure` under the hood. I don't think there's any way I can get around that.

**Comment by arnog** [comment] 2023-02-17 04:19
Sigh... OK, I'll see if I can restore the UMD support.

**Comment by arnog** [comment] 2023-02-17 17:13
OK, I've tried to add UMD support back. Unfortunately, I don't have a test environment to verify it works. Could you give it a try and confirm that this fixes it? Try mathlive 0.89.2.

**Comment by AllyMarthaJ** [comment] 2023-02-18 00:44
You are an absolute gem, thank you so much. I've checked and it works.
I've also raised that we should move away from the way we do our requires/imports (i.e. a project to upgrade).

**Comment by arnog** [comment] 2023-02-18 01:08
Great! Thanks for letting me know. Closing.

**Closed by arnog** 2023-02-18 01:08 UTC
