### ISSUE TITLE
React bindings

### ISSUE THREAD

**Issue by ShaMan123** [arnog/mathlive#767] opened 2020-12-20 17:41 UTC
## Description

This is a fantastic library!
Are you interested in `react` bindings?
I think it could be neat as an opt in import such as `mathlive/react` or as a different package such as `mathlive-react`.
For the time being I've published the bindings under [react-math-view](https://github.com/ShaMan123/react-math-view#react-math-view).
However I do think it should be part of this repo or under your user.
Thanks!

**Comment by arnog** [comment] 2020-12-20 19:20
Thank you for your kind words! Glad you like it.

Yes, I think some React bindings packaged with the library would make sense. I get regular request for some, and there are already Vue.js bindings in the distribution. There is also an existing React bindings package for MathLive at https://github.com/concludio/react-mathlive , although it is based on the old functional API rather than the more recent web component.

If you'd like to submit a PR, I'd be happy to review it and merge it.

**Comment by ShaMan123** [comment] 2020-12-21 06:46
Great!
So I'm having some thoughts, wanted your feedback.
Should the react bindings be a submodule? or should it be a sub-package under the repo?
- **submodule**: I can pull `react-math-view`, easy enough.
- **sub-package**: I think it should be completely independent and opt-in so it could be packed and distributed separately. Having `mathlive` as a dependency does the job, but there could/should be a better way I am unaware of. What do think? Maybe some build task?
Optional structure:
├── src
│   ├── ...
│   └── **react**
├── examples
│   ├── ...
│   └── **react**
└── ...
Should the `example/react` directory include source files or only outputs? If so the source files could reside in `src/react/example` and be emitted to `examples/react` but it sounds error prone.

**Comment by arnog** [comment] 2020-12-21 07:49
I have found that having the bindings as plain file(s) in the Mathlive depot is the easiest way to go. See `src/vue-mathlive.js`, which are the bindings for Vue.js. If the bindings can't fit in a single file, I would add a `src/react` directory, but I would try to make it work in a single file first.

As for the example, it's a bit tricky. The easiest thing might be to have a separate `react-mathlive` repo to host the example (I assume the issue is that in order to use jsx/React you need specific build/bundle steps in order to generate a runnable example?) That approach would be consistent with the existing `vue-mathlive` repo which similarly serves as a standalone example for the Vue.js bindings (although the Vue examples is *also* in `/examples` since it doesn't require special build steps).

**Comment by ShaMan123** [comment] 2020-12-21 08:34
As you mentioned, there are special build steps and config files. So I don't see a way of putting it all into a single file.
Regarding the example, I think it's best for the source files to reside under `examples/react`, serving the `build` directory.

**Comment by arnog** [comment] 2020-12-21 08:54
ok, I've created the `arnog/react-mathlive` repo which you can use if you'd like.

**Comment by ShaMan123** [comment] 2020-12-24 22:49
continuing there

**Comment by arnog** [comment] 2020-12-25 13:38
Closing, moving to `arnog/react-mathlive`

**Closed by arnog** 2020-12-25 13:38 UTC
