### ISSUE TITLE
How to display the text in next line 

### ISSUE THREAD

**Issue by imsummit18** [arnog/mathlive#2564] opened 2024-12-10 11:33 UTC
y=cx+2-k 
y=5 
In the system of equations above, c and k are constants. For which of the following values of c and k does the system of equations have no real solutions?

When I am typing this kind of questions, the description for the question is long . I want to make the long text go to next line if it is too long while displaying it.

**Comment by arnog** [comment] 2024-12-10 12:53
Sounds like a dupe of https://github.com/arnog/mathlive/issues/598

**Closed by arnog** 2024-12-10 12:53 UTC
