### ISSUE TITLE
Fixing parens manually triggers malformed MathJSON

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1742] opened 2022-12-04 15:54 UTC
## Description

(@jefffriesen found this while playing with https://github.com/mentat-collective/mathlive.cljs/issues/11.)

to repro:

- type an expression like `1+cos()y`
- decide you want to pull `y` into the parens
- delete the right paren and retype it to the right of `y`

The `Mathfield` eagerly inserts a multiplication dot and parses the input as

<img width="186" alt="image" src="https://user-images.githubusercontent.com/69635/205501196-90bc6670-a6b8-4b84-8f0f-7fca331c36ad.png">

Full interaction:

![2022-12-04 08 48 41](https://user-images.githubusercontent.com/69635/205500976-6a0e8825-4abd-49a5-a62d-16c107ec6d41.gif)

MathJSON:

```
[
  "Sequence",
  [
    "Add",
    1,
    [
      "Sequence",
      [
        "Cos",
        [
          "Error",
          [
            "ErrorCode",
            "'expected-close-delimiter'",
            "\\right)"
          ],
          ["Latex", "'('"]
        ]
      ],
      [
        "Error",
        ["ErrorCode", "'expected-open-delimiter'", "\\left"],
        ["Latex", "'\\right.'"]
      ],
      "y"
    ]
  ],
  [
    "Error",
    ["ErrorCode", "'expected-open-delimiter'", "("],
    ["Latex", "')'"]
  ]
]
```

**Comment by arnog** [comment] 2022-12-05 02:32
I think that's a duplicate of #1656

**Comment by gerryfletch** [comment] 2023-01-03 23:37
I'm noticing this quite frequently with parens, especially because if I type `(` it'll create the corresponding `)` for me, but pressing backspace to write into it creates the `.`

**Comment by arnog** [comment] 2023-04-19 05:12
Fixed now.

**Closed by arnog** 2023-04-19 05:12 UTC
