### ISSUE TITLE
How to handle mathlive.mjs with webpack

### ISSUE THREAD

**Issue by zwz** [arnog/mathlive#525] opened 2020-07-03 12:43 UTC
I was using https://github.com/sveltejs/template-webpack
And only one line, that is `import 'mathlive'`, is added into `App.svelte` 
```
<script>
 import 'mathlive'
 ......
</script>
```

And When I run `npm run dev`, it reports error:
```
ERROR in ./node_modules/mathlive/dist/mathlive.mjs 2:180267
Module parse failed: Unexpected token (2:180267)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /* MathLive 0.53.3  */
<here is the code of mathlive ...>
```

Is there any required setup of webpack to use mathlive?

**Comment by arnog** [comment] 2020-07-03 23:44
This is a duplicate of #508 ("`import.meta` causes issues").

Basically, MathLive uses `import.meta.url` to find the directory/URL where the script is, and from there locate the default folder from which to load fonts.

Unfortunately, `import.meta` is not supported by WebPack (see https://github.com/webpack/webpack/issues/6719). 

This WebPack issue has been discussed for over two years now, so I don't expect an imminent resolution.

I am looking into a workaround but don't have a solution yet.

**Comment by zwz** [comment] 2020-07-04 06:04
I see.
So do you know any bundler that can handle `import.meta` ?

**Comment by arnog** [comment] 2020-07-04 06:28
`rollup` seems to have no problem (that's what MathLive uses). I understand that `parcel` is fine with it as well. Actually, AFAIK, only WebPack seems to have some difficulties implementing `import.meta`.

**Comment by physedo** [comment] 2020-07-04 18:52
`[ng] ERROR in ./node_modules/mathlive/dist/mathlive.mjs 2:180308
[ng] Module parse failed: Unexpected token (2:180308)
[ng] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[ng] | /* MathLive 0.54.0  */
`
I have also this issue

**Comment by Paosder** [comment] 2020-07-20 02:16
I used some tricky way to resolve this.

Replace `import.meta.url` variable to static characters(e.g "https://test.com/test").
  I used [`replace`](https://www.npmjs.com/package/replace) package for replace value above, execute when dependencies are updated(using `prepare`).

> "prepare": "replace \"import.meta.url\" \"'https://test.com/share/mathlive/fonts'\" node_modules/mathlive/dist/mathlive.mjs"

Then you can use webpack, esbuild, or any other bundlers without meta related issue.

**Comment by arnog** [comment] 2020-07-20 03:58
FYI, I have a fix pending that will remove the need for import.meta.url. I just need to do a bit more testing.

**Comment by 2010hexi** [comment] 2020-08-01 17:50
> FYI, I have a fix pending that will remove the need for import.meta.url. I just need to do a bit more testing.

hi , do you have any progress about import the mathlive in any  vue file?

**Comment by arnog** [comment] 2020-08-01 21:34
Sorry, I've been distracted by some personal matter. I'll try to make some time to get this finished and pushed to the repo ASAP.

**Comment by rojer95** [comment] 2020-08-11 13:46
Same need

**Comment by 2010hexi** [comment] 2020-08-11 13:57
@rojer95  i use  this  approach to use the mathlive into my webpack project, https://www.jianshu.com/p/60eb28559f59 this is my blog check if it helps or not

**Comment by FI-LIFE** [comment] 2020-08-17 11:46
@arnog hi, do you have news?

**Comment by arnog** [comment] 2020-08-17 18:23
Sorry for the delay. I have checked in a fix. I'll publish a build shortly. More information about how to integrate Mathlive with various configurations, including Webpack, is now available here: http://cortexjs.io/guides/mathfield-getting-started/

**Closed** 2020-08-17 18:27 UTC
Labels: feature

**Comment by 2010hexi** [comment] 2020-08-19 05:16
> Sorry for the delay. I have checked in a fix and published mathlive@0.55.0.
> 
> More information about how to integrate Mathlive with various configurations, including Webpack, is now available here: http://cortexjs.io/guides/mathfield-getting-started/

hi @arnog, I follow your steps to  test it using NPM 
and it shows the error
```
 ERROR  Failed to compile with 1 errors                                                                                                             1:11:10 ├F10: PM┤
 error  in ./node_modules/_mathlive@0.55.0@mathlive/dist/mathlive.mjs

Module parse failed: Unexpected token (2393:21)
You may need an appropriate loader to handle this file type.
|         this.sizeMultiplier = multiplier;
|         this.metrics = Object.keys(SIGMAS).reduce((acc, x) => {
|             return { ...acc, [x]: SIGMAS[x][this.size] };
|         }, {});
|         this.metrics.emPerEx =

 @ ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_vue-loader@13.7.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloWorld.vue 8:0-32
 @ ./src/components/HelloWorld.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@2.11.5@webpack-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js
```
My steps as follow:
1. vue init webpack  test_mathlive0.55
2. npm install --save mathlive
3.  in the HelloWorld.vue file add the code 
```js
<template>
  <div class="hello">
    <div id="formula">f(x)</div>
  </div>
</template>

<script>
import MathLive from 'mathlive';
const mathfield = MathLive.makeMathField('formula');

export default {
  name: 'HelloWorld',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
```

4. run the code , it fail to run and shows the error above.

Can you help check it ?

**Comment by arnog** [comment] 2020-08-19 16:04
This seems to be an issue with your babel configuration, specifically, its handling of the spread operator. See https://github.com/babel/babel/issues/9675 and https://www.npmjs.com/package/@vue/babel-preset-app and the "polyfills" section.

**Comment by arnog** [comment] 2022-04-14 15:30
Two years later, but there is still an issue in the toolchain. Webpack 4, in particular, does not support the optional chaining operator (although all evergreen browser do). To work around this MathLive is now packaged differently:
- the `mathlive.min.js` library is compiled targeting an older version of JavaScript that should be compatible with Webpack 4
- the `mathlive.min.mjs` library is compiled for up to date toolchains.

So, if you run into errors integrating MathLive, try to use the `dist/mathlive.min.js` library.
