### ISSUE TITLE
Multiline shortcut produces invalid LaTeX

### ISSUE THREAD

**Issue by AllyMarthaJ** [arnog/mathlive#2000] opened 2023-06-01 05:16 UTC
## Description

When using the inline shortcut for inserting multiline content, invalid MathLive content is produced.

## Steps to Reproduce

1. Go to MathLive demo at https://cortexjs.io/mathlive/demo/.
2. Enter some text, e.g. `a`. Then use the inline shortcut e.g. Mod-Enter and type `b`. 
3. Copy the resultant LaTeX, refresh, and input the LaTeX into the field. (It is something of the form `\begin{lines}a\\ b\end{lines}`)
4. Observe the MathLive field no longer renders the multiline content.

Associated screenshots:

Before:
<img width="249" alt="image" src="https://github.com/arnog/mathlive/assets/28497049/94cdd576-94d4-4407-abb1-6eb210f326f4">

After:
<img width="274" alt="image" src="https://github.com/arnog/mathlive/assets/28497049/4745dd11-248c-483c-8d23-cb301680f463">

This is reproducible on an external platform too.

### Actual Behavior

Invalid MathLive LaTeX is produced.

### Expected Behavior

The LaTeX should be able to be re-used within the MathLive editor.

### Environment

**MathLive version**
0.94.6

**Comment by arnog** [comment] 2023-07-04 21:43
Fixed with https://github.com/arnog/mathlive/commit/e9925484eeb5715db061d96475e3fef934496c3a

**Comment by AllyMarthaJ** [comment] 2023-07-05 06:41
This is still an issue on latest version.

**Comment by arnog** [comment] 2023-07-05 12:31
I cannot reproduce it. Can you check you are using 0.95.0? (On the MathLive Demo page the version is indicated at the bottom of the page).

I followed the steps in the issue report. Is there something missing?

When you say "reproducible on external platform", what do you mean?

**Comment by AllyMarthaJ** [comment] 2023-07-05 13:01
If you paste the above LaTeX on the demo page, it still fails to render with the same failure points as pictured.

Unless I'm misunderstanding the fix, the environment shouldn't have changed right?

**Comment by arnog** [comment] 2023-07-05 13:21
What OS/browser are you using?

And so that we’re on the same page, the issue occurs not when following the steps in the original report, but if you copy ` \begin{lines}a\\ b\end{lines}` and paste it into the mathfield?

**Comment by AllyMarthaJ** [comment] 2023-07-05 23:02
Yeah; I followed the same steps as before.

https://github.com/arnog/mathlive/assets/28497049/1cd75222-25e4-4134-b625-45a5a831310e

Chrome 114.0.5735.198 (Official Build) (arm64) 
macOS 13.2.1 (22D68)

**Comment by AllyMarthaJ** [comment] 2023-07-05 23:13
As for why pasting is relevant: this same issue occurs when you programatically load in the LaTeX via setValue or otherwise (so for my usage, I have an editor, which when previewed will render the LaTeX incorrectly as above)

**Comment by arnog** [comment] 2023-07-05 23:54
Ah, OK, I get it now. I thought you were copying and pasting from the mathfield, which was broken but is working now. I thought that was the issue.

There is indeed another issue when pasting LaTeX copied from elsewhere (or when setting the value directly). Thank you, this helps.

**Comment by AllyMarthaJ** [comment] 2023-07-06 03:34
No, thank you! Sorry for the ambiguity haha

**Closed** 2023-12-11 00:29 UTC
Labels: bug
