### ISSUE TITLE
Some signs are impossible to get (try \infty or \int)

### ISSUE THREAD

**Issue by jlchereau** [arnog/mathlive#199] opened 2019-05-19 11:05 UTC
> DISCLAIMER: I need to dig into this one further, because apparently mathlive changes behavior at some point: it no more displays tooltips and \in is changed in the "element of" sign as soon as n is typed. I have experienced this change recurrently but I have not yet found a set of steps that triggers the behavior.

**Describe the bug**

Some signs are impossible to get

**To Reproduce**

1. Go to mathlive.io
2. Type `\infty`
3.  You get:

![image](https://user-images.githubusercontent.com/2556751/57981329-e2480b00-7a2d-11e9-8e14-0b16b6d5237e.png)

The only way I have found to get

![image](https://user-images.githubusercontent.com/2556751/57981338-fa1f8f00-7a2d-11e9-97ab-59bc268a6ab4.png)

Is to copy paste `\infty`

Same thing in a sum:

![image](https://user-images.githubusercontent.com/2556751/57981496-145a6c80-7a30-11e9-910c-9725c4a93ab6.png)

**Expected behavior**
Copy-paste and typing should get you the same results.
Try the same in mathquill.com

**Environment**
- Device: PC
- OS: Windows 10
 - Browser Chrome
 - Version v0.29.0

**Comment by arnog** [comment] 2019-05-19 17:11
What kind of keyboard are you using? Is it an AZERTY keyboard? Is the "/" key you are using on the main keyboard or on a numeric keypad?

**Comment by jlchereau** [comment] 2019-05-19 17:13
I am using a QWERTY keyboard, but this is not the issue,
MathLive is not consistent in the way it behaves. See DISCLAIMER added at the top.

**Comment by arnog** [comment] 2019-05-19 17:29
I was asking this because based on your screenshot in #198 it appears that you have somehow gotten out of command mode. It could have been because of your keyboard layout (there have been problems with this in the past, and specifically with the / key).
I cannot reproduce what you are describing in this bug report, so there must be some steps that are missing.

**Comment by arnog** [comment] 2021-04-23 20:12
The Latex mode has been rewritten since this issue was filed. I tried to reproduce it, but still no luck. Closing for now, but please reopen if you still see this issue.

**Closed by arnog** 2021-04-23 20:12 UTC
Labels: unable to reproduce

**Comment by jlchereau** [comment] 2021-04-24 05:11
Typing \ no more puts mathlive in command mode but the problem still subsists.

Typing "**sum**" into a mathlive field via keyboard gives:

![image](https://user-images.githubusercontent.com/2556751/115948038-9b89a800-a4c3-11eb-86e2-de2384312d33.png)

Typing "**int**" gives:

![image](https://user-images.githubusercontent.com/2556751/115948060-b5c38600-a4c3-11eb-87e0-3719fd0a2cfd.png)

Typing "**infty**" gives:

![image](https://user-images.githubusercontent.com/2556751/115948084-d8ee3580-a4c3-11eb-877f-80cdd90582c8.png)

**Comment by arnog** [comment] 2021-04-24 10:02
You can define custom inline shortcuts. See https://cortexjs.io/mathlive/guides/shortcuts/

Neither `infty` nor `int` were defined as inline shortcuts, so it seems like the current behavior is as expected. However, I've added them both as default inline shortcuts, so they will produce the corresponding Latex now.

Pressing the "\" key should switch to Latex (command) mode. If that is not working for you, I'd like to know which kind of keyboard you have and which country you're in (the keyboard layout is country dependent).

**Comment by jlchereau** [comment] 2021-04-24 10:15
I use a Corsair K70 with Qwerty UK Layout: https://www.amazon.co.uk/Corsair-Mechanical-Gaming-Keyboard-Switches/dp/B07DNSTH51

Pressing `\` (key between Shift and Z) does not trigger command mode. For example typing `\sum` gives the following result:

![image](https://user-images.githubusercontent.com/2556751/115955455-647cbc00-a4ee-11eb-8265-d51a7d6dc488.png)

**Comment by arnog** [comment] 2021-04-24 11:11
OK, thanks, that's helpful.

So, it turns out that that key is unique to the UK QWERTY keyboard (although the Brazilian keyboard may have it as well).

I've tried to implement a fix in 0.63.1 but it's impossible for me to test it without a physical keyboard, so let me know if that fix works. If not, I'll have to find myself a UK keyboard.

**Comment by arnog** [comment] 2021-04-24 11:14
Oh, I should also mention that pressing the ESC key will also switch to Latex mode. Still, I'd love to get this "international backslash" key to work...

**Comment by jlchereau** [comment] 2021-04-24 11:16
On windows, I can reproduce with the on-screen keyboard which you might be able to configure as UK Qwerty or Brazilian.

![image](https://user-images.githubusercontent.com/2556751/115956801-dc4ee480-a4f6-11eb-99f5-df2deb080e06.png)

**Comment by jlchereau** [comment] 2021-05-29 10:54
I can confirm command mode now works with UK keyboard (v0.67.0). Thx.

**Comment by arnog** [comment] 2021-05-29 18:35
🎉
