### ISSUE TITLE
One letter variable names only

### ISSUE THREAD

**Issue by ro70** [arnog/mathlive#2143] opened 2023-09-21 19:35 UTC
Hello

The expression "2xy" parses to

```
["Multiply", 2, "xy"]
```

I haven't found an option to parse it to

```
["Multiply", 2, "x", "y"]
```

Is this really not possible?

**Comment by arnog** [comment] 2023-09-21 23:04
It's hard to tell with the information provided in this report. Please try to follow the issue template.

What code did you run? 

If you run `ce.parse("2xy")` you should get `["Multiply, "2", "x", "y"]`. 
If you run `ce.parse("2\\mathrm{xy}"), you should get `["Multiply, 2, "xy"]`.

What was the configuration of your mathfield? Did you have a mathfield setup to consider multiple characters as one identifier? Like the page at https://cortexjs.io/compute-engine/demo/? If so, the output of the mathfield is `2\mathrm{xy}`, and the correct answer is indeed `["Multiply", 2, "xy"]`.

I can't reproduce the issue with the information provided.

**Comment by ro70** [comment] 2023-09-22 08:15
Sorry for not following the template.

I just played around with the mathfield on the page https://cortexjs.io/compute-engine/demo/. There the input "2xy" leads to the MathJSON `["Multiply", 2, "xy"]`. You mention the mathfield setup. How do I have to set the mathfield to get `["Multiply", 2, "x", "y"]` instead?

**Comment by arnog** [comment] 2023-09-22 13:33
Just use the default Mathfield. Note that on the demo page, if you type a space between the "x" and the "y" they will be interpreted as two distinct variables.

**Closed** 2023-09-22 17:05 UTC
Labels: does not follow template
