### ISSUE TITLE
Hiding the virtual-keyboard-toggle still leaves a small amount of padding

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2101] opened 2023-08-20 13:37 UTC
My application does not use the virtual keyboard, so I have tried to hide it using this CSS:

       math-field::part(virtual-keyboard-toggle) {
            display: none;
        }
        
however this doesn't completely reclaim all of the space and there is still something using space.  Below is an image that shows what I mean.  Here you can see that although I filled the math field with 8s, there is still a gap on the right.

<img width="425" alt="Screenshot 2023-08-20 at 21 28 17" src="https://github.com/arnog/mathlive/assets/39233783/5c613c65-0cfb-4766-bc08-ab6e82a6ed2c">

I tried to comment this out in the JS

    // markup.push("<span class=ML__sr-only>");
    // // markup.push(
    // //   "<span role=status aria-live=assertive aria-atomic=true></span>"
    // // );
    // markup.push("</span>");
    
but there is still something to the right of the 8s, and I cannot see what it is with the developer tools, as whenever I tap the screen the virtual-keyboard-toggle image appears again.

Is there some way that you can suggest to remove the space occupied by the blue square in the image below?

<img width="425" alt="Screenshot 2023-08-20 at 21 28 17" src="https://github.com/arnog/mathlive/assets/39233783/96f68627-f3e0-44fb-821f-a3d333e35e54">

**Comment by arnog** [comment] 2023-08-20 15:18
I cannot reproduce this.

<img width="683" alt="Screenshot 2023-08-20 at 08 17 18" src="https://github.com/arnog/mathlive/assets/760798/04eacc1a-57e9-40e9-8d64-4b64d4b6d420">

Are you applying some other CSS rules to the math-field?

**Comment by rs-mobitech** [comment] 2023-08-20 16:31
Here is the CSS that I am applying

```
<style>

    math-field::part(virtual-keyboard-toggle),
    math-field:focus-within {
        display: none;
        outline: none;
    }

    .mf {
        background-color: #CCCCCC;
        --caret-color: red;
        --selection-background-color: lightgoldenrodyellow;
        --selection-color: darkblue;
        margin: 0;
        padding: 0;
        font-size: 20px;
        padding: 3px;
    }
    body {
        background-color: #BBBBBB;
        margin: 0;
        padding: 0;
    }
</style>
```

**Comment by rs-mobitech** [comment] 2023-08-20 16:41
I am just trying to repeat this myself and now I don't see the problem. My apologies as this might be a false alarm.  I will try again tomorrow, to see if I can reproduce the problem.

**Comment by arnog** [comment] 2023-08-20 17:53
That CSS rule is probably incorrect:

```css
    math-field::part(virtual-keyboard-toggle),
    math-field:focus-within {
        display: none;
        outline: none;
    }
```
It says: "when the mathfield is focused, hide it". That is probably not what you want. Instead, you probably want:

```css
    math-field::part(virtual-keyboard-toggle)
        display: none;
    }
    math-field:focus-within {
        outline: none;
    }
```

I don't know if that's the source of your issues, though.

Also, I can't reproduce the issue you were having with scrollToEnd. It works fine for me.

**Comment by rs-mobitech** [comment] 2023-08-21 07:35
Thanks for your advice.  I believe my problems are solved now.

**Comment by arnog** [comment] 2023-08-21 14:40
Closing.

**Closed by arnog** 2023-08-21 14:40 UTC
Labels: unable to reproduce
