### ISSUE TITLE
Keyboard doesn't display when mathfield appending dynamicly.

### ISSUE THREAD

**Issue by Chrisb0606** [arnog/mathlive#1535] opened 2022-07-04 14:42 UTC
First of all, I've found out an issue that happens only when I add custom Keyboards.
For the time being, I append dynamically a mathfield in the DOM and it works great with standard keyboards.
I've decided to implement a customKeyboard and mathfield behaves differently depending on the order I append the mathfield into the DOM.

My initial code that works well with standard keyboards : 

```javascript
let divContainer = document.createElement('div');
let answerMathField = new MathfieldElement();
answerMathField.setOptions({
   defaultMode: "math",
   virtualKeyboardMode: "manual",
   virtualKeyboards: "numeric greek"
}
divContainer.appendChild(answerMathField);
document.body.appendChild(divContainer);
```

Once I add a custom virtualKeyboard in the list  

`virtualKeyboards: "numeric greek my-custom-keyboard`

It turns out that the show/hide button does not display the keyboard entirely (in fact it only triggers the display of a small line appearing at the bottom of the document.

https://user-images.githubusercontent.com/47278321/177175626-ba8ff258-22a8-4aa8-94c1-5d0435ceb3cf.mov

---

If I reversed the appending calls, it works well again :

```javascript
document.body.appendChild(divContainer);
divContainer.appendChild(answerMathField);
```

https://user-images.githubusercontent.com/47278321/177175997-f5ac81f5-4531-4d58-b2fc-eb0128affbf7.mov

Thanks for your help.
Chris

**Comment by arnog** [comment] 2022-07-04 17:13
I can't reproduce this with the code you have provided. There must be something else that's interfering.
- Do you have any error messages in the console?
- Are you using `makeSharedVirtualKeyboard()`
- Do you specify a custom container for the keyboard

Could you provide an isolated code example that reproduces the problem?

**Comment by Chrisb0606** [comment] 2022-07-04 19:24
I've tried to isolate the problem with a sandbow and I didn't reach that.
- I have no errors in the console : is there a flag to enable debug mode or a more verbose mode. Moreover could I set the keyboard always visible for deguging purposes, because I can't find a way to explore the keyboard in the DOM in the browser's debugger : it automaticaly hides itself because when I try to manipulate or explore the DOM code the keyboard hides (it considers my exploration as a click outside the keyboard)... 
- If I use makeSharedVirtualKeyboard(), it works but my custom keyboard is ignored.
When I use makeSharedVirtualKeyboard, I've coded like that : 
`makeSharedVirtualKeyboard();
  answerMathField = new MathfieldElement({
    virtualKeyboardMode: "manual",
    customVirtualKeyboardLayers: INTEGER_KEYBOARD_LAYER,
    customVirtualKeyboards: INTEGER_KEYBOARD,
    virtualKeyboards: "integer",
  });
`
- I do not specify container for the keyboard. Once created, I just append it into a div within the DOM.
Thanks for your help.

**Comment by arnog** [comment] 2022-07-04 21:53
- There is no verbose mode, but there would be some errors in the console if there was a problem with your custom keyboard
- To have the keyboard always visible, set the `virtualKeyboardMode` to `"off"`, then call `mf.executeCommand("showVirtualKeyboard")`.
- I just found out that there is a bug when using `makeSharedVirtualKeyboard()`. If you reveal the keyboard by clicking on the virtual keyboard toggle **before** focusing the mathfield, the custom keyboard is not taken into account. However, if you focus the mathfield first before toggling the keyboard, it will be correctly configured.

Still no idea why your initial issue happened. If you can find a reproducible case you can share, I'd be happy to look at it.

**Comment by arnog** [comment] 2022-07-04 22:17
I fixed the bug with the incorrect options when clicking on the virtual keyboard toggle button of an unfocused mathfield.

**Comment by Chrisb0606** [comment] 2022-07-08 11:13
Thanks. 
I didn't reach to isolate the problem. I finally decide to reverse the order I append Nodes in the DOM (it's not dramatic on my side).
I also achieve to make makeSharedVirtualKeyboard() works and I've figured that I can share and also change the keymap attached. That's great because I have many fields on the same page (for instance, one to input a fraction one to input an integer, one to input an expression) and the mathfield layer displayed changes dynamicaly without blinking (I mean without closing and opening again).
Chris

**Comment by arnog** [comment] 2022-07-08 16:40
Yes, when using multiple mathfield elements on a page, using `makeSharedVirtualKeyboard()` will result in a better user experience.
Closing for now, but if you run into a reproducible case along the lines of what you first described, don't hesitate to re-open or file a new issue.

**Closed by arnog** 2022-07-08 16:40 UTC
Labels: unable to reproduce

**Comment by Chrisb0606** [comment] 2022-07-09 21:20
Hi, I've finally reached to isolate this issue.
You can see there : https://codesandbox.io/s/mathfield-bug-when-customekeyboard-yyqlez?file=/src/index.js
Thanks
