### ISSUE TITLE
Overflow text into multi-lines instead of horizontal scroll 

### ISSUE THREAD

**Issue by evyatarbh** [arnog/mathlive#1238] opened 2021-11-15 16:38 UTC
## Description

We are using MathLive as a formula editor and need to prevent horizontal scrolling.
Instead, we want lines to break on math symbols (i.e. not break on words, which should overflow to next line).
Text-area height should increase automatically according to the content's height.

We're currently using MathLive version 0.59.0

**Comment by arnog** [comment] 2021-11-19 09:52
That sounds like a duplicate of #224. If that is the case, I would suggest you add a comment to that issue detailing your use case.

**Closed** 2022-06-20 23:19 UTC
Labels: duplicate
