### ISSUE TITLE
Is there any way to display not broken layout on ios 15.7?

### ISSUE THREAD

**Issue by insoohyeon** [arnog/mathlive#2133] opened 2023-09-08 08:18 UTC
## Description

<img width="369" alt="image" src="https://github.com/arnog/mathlive/assets/46772628/a7413a3b-f019-4ca4-96dc-922fc8372bfa">

- I know there was already issue about this. #2027, #2028
- Some of my clients are using on ios 15.7 version. So when I updated the newest version and checked on ipad, I was surprised.
- I want to know how to display not broken keyboard on ios 15.7(except update ios 16)
- Is there any way?

### Environment

**MathLive version**  
: 0.95.5

**Operating System** 
: ios 15.7
: ipad safari

**Comment by arnog** [comment] 2023-09-08 17:10
At this point, iOS 16 is the minimum supported release.

**Comment by insoohyeon** [comment] 2023-09-11 08:37
ok Thank you for reply.

**Comment by arnog** [comment] 2023-09-11 23:12
Closing. Dupe of #2028

**Closed by arnog** 2023-09-11 23:12 UTC

**Comment by arnog** [comment] 2023-09-19 17:06
In general, I try to support older version of OS (although using older versions of OSes is bad practice from a security standpoint, I do understand that it may be difficult in some education environment to keep devices up to date).

However, when some new features or capabilities are introduced that are not supported in older versions, I will attempt to implement a workaround, if it is simple. If it requires too much work, unless someone is willing to sponsor the work, I'm not likely to spend time on it. 

In this particular case, iOS 16 introduced support for CSS container queries, which are used to do responsive layout of the virtual keyboard, i.e. so you can display a virtual keyboard for example in an iframe without the keyboard taking the whole width of the screen.

An attempt was made to introduce a simple workaround, but it ended up breaking other things, so I had to back it out. I have an idea on how a workaround could be implemented, but it's a substantial amount of work, and I suspect the number of users relying on OS pre-iOS 16 will diminish over time.
