### ISSUE TITLE
No keyboard in iOS

### ISSUE THREAD

**Issue by FlashTang** [arnog/mathlive#676] opened 2020-10-20 22:10 UTC
Hi,no keyboard pop up when I tap on the text field of the demo website mathlive.io, any idea? Both iOS 11 and iOS 13
Thanks

**Comment by arnog** [comment] 2020-10-21 06:41
That's very strange, it seems to be working for me. 

Did you try it on the main page of mathlive.io or on one of the "examples" pages? The "Basic Example" page is setup so that the keyboard only shows up if you click on the virtual keyboard toggle button. This is a behavior you can control when creating a mathfield using the [`virtualKeyboardMode`](http://cortexjs.io/docs/mathlive/?q=virtualkeyboardmode) option.

**Comment by FlashTang** [comment] 2020-10-21 12:42
@arnog 
Hi  @arnog  , yes very strange, it works in laptop, but not in my phones (Android or iOS iPhone iPad) 
I tried both main page and  examples pages , all not working
the main page's "Examples" drop down menu is empty , and there are no toggle button in the "Basic Example" pages, just an empty textfield
seems there is network issue ? but my phones use the same network with laptop ,I also tried with VPN , the same vpn ,laptop works but not in phones (the laptop works with VPN or without VPN, phones not working with or wothout VPN)
And now I have 2 questions :
1:  Is Mathlive possible to work in local (without server) ?
Since I want to use Mathlive in my iOS app (MindMap app allows user to add equation to the node) with WKWebView 
I just tried Mathjax ,it works perfectly , but it's unpractical to let user type LaTex (particularly in mobile phone)
2: If it works without server  locally ,then I think I can use Mathlive as the keyboard (outputs LaTex string) ,then display with Mathjax (by using LaTex string from Mathlive) , but I don't know if it's a good idea or I should use Mathlive directly without Mathjax
Thank you

**Comment by arnog** [comment] 2020-10-21 13:51
This does sound like a networking issue...

1/ Yes, MathLive can be used locally, for example with a webview. The only "tricky" (it's not that tricky) thing is that you need to include the necessary fonts (the ones in the `dist/fonts` directory) in your app bundle, and configure MathLive so it can find them. See the "Controlling the location of the fonts folder" section in the [Getting Started](http://cortexjs.io/guides/mathfield-getting-started/) guide.

2/ You can use MathJax to render the output from MathLive, but you can also use MathLive to do the same, using [`renderMathInElement()`](http://cortexjs.io/docs/mathlive/#(%22mathlive%22%3Amodule).(renderMathInElement%3Afunction)) or [`renderMathInDocument()`](http://cortexjs.io/docs/mathlive/#(%22mathlive%22%3Amodule).(renderMathInDocument%3Afunction))

**Comment by FlashTang** [comment] 2020-10-22 04:11
@arnog Great ! , but I still have problem
This is the html file I use :
```
<!DOCTYPE html>
<html>
<body>
    <script src='./js/mathlive.min.js'></script>
    <script>
        const mfe = new MathfieldElement();
        mfe.setOptions({
    		fontsDirectory: '../fonts'
		});
		mfe.value = '\\frac{\\pi}{2}';
		document.body.appendChild(mfe);
    </script>
</body>
</html>
```
It remders like this : (but no error in the chrome console , the fonts seems to be loaded successfully)
![Screen Shot 2020-10-22 at 11 45 18 AM](https://user-images.githubusercontent.com/920751/96822303-51fcc980-145c-11eb-8404-a0b130092733.png)

![Screen Shot 2020-10-22 at 11 44 16 AM](https://user-images.githubusercontent.com/920751/96822153-fc282180-145b-11eb-9c2b-58152a4f3349.png)

If I use the js file hosted in unpkg.com , it works fine 
```
<!DOCTYPE html>
<html>
<body>
    <script src='https://unpkg.com/mathlive/dist/mathlive.min.js'></script>
    <script>
        const mfe = new MathfieldElement();
		mfe.value = '\\frac{\\pi}{2}';
		document.body.appendChild(mfe);
    </script>
</body>
</html>
 
```

![Screen Shot 2020-10-22 at 11 45 18 AM](https://user-images.githubusercontent.com/920751/96822651-24fce680-145d-11eb-8e94-fb2fb63947d4.png)

Another problem with following code , get error
```
<!DOCTYPE html>
<html>
<body>
    <p>$$\frac{\pi}{2}</p>
    <script src="https://unpkg.com/mathlive/dist/mathlive.min.js"></script>
    <script>
        MathLive.renderMathInDocument();
    </script>
</body>
</html>
```
Uncaught TypeError: MathLive.renderMathInDocument is not a function
    at test.html:6

![Screen Shot 2020-10-22 at 11 58 36 AM](https://user-images.githubusercontent.com/920751/96823000-f7fd0380-145d-11eb-8c8d-efe2869a4dc0.png)

Thanks

**Comment by arnog** [comment] 2020-10-22 09:32
OK, I'm going to spend some time investigating. Stay tuned.
For the second problem, you can try:
```
<!DOCTYPE html>
<html>
<body>
    <p>$$\frac{\pi}{2}$$</p>
    <script type="module">
       import {renderMathInDocument} from "https://unpkg.com/mathlive/dist/mathlive.min.mjs";
       renderMathInDocument();
    </script>
</body>
</html>

```

**Comment by FlashTang** [comment] 2020-10-22 09:46
> OK, I'm going to spend some time investigating. Stay tuned.
> For the second problem, you can try:
> 
> ```
> <!DOCTYPE html>
> <html>
> <body>
>     <p>$$\frac{\pi}{2}$$</p>
>     <script type="module">
>        import {renderMathInDocument} from "https://unpkg.com/mathlive/dist/mathlive.min.mjs";
>        renderMathInDocument();
>     </script>
> </body>
> </html>
> ```

@arnog  Hi arnog , just tried the code you provided, but error :

Uncaught SyntaxError: The requested module 'https://unpkg.com/mathlive/dist/mathlive.min.mjs' does not provide an export named 'renderMathInDocument'
Chrome console 
![Screen Shot 2020-10-22 at 5 43 42 PM](https://user-images.githubusercontent.com/920751/96854703-622d9c80-148e-11eb-80cf-89af9399e98b.png)

Safari console 
![Screen Shot 2020-10-22 at 5 43 11 PM](https://user-images.githubusercontent.com/920751/96854798-7d001100-148e-11eb-8a87-d8c626ee2568.png)

**Comment by arnog** [comment] 2020-10-22 10:45
Ah, I got it, for the first error at least: you need to serve your `index.html` file from a local server, you can't open it as a local file. Due to CORS restrictions the assets (fonts in this case) cannot be loaded locally by the browser. And the (non-existent) error messages are not very helpful. If you want to use a `WKWebView`, [this article](https://medium.com/@zzdjk6/wkwebview-cors-solution-da20ca1194e8) contains info about how to configure it for this situation.

**Comment by arnog** [comment] 2020-10-22 10:48
For the second issue, the following will work:
```
<!DOCTYPE html>
<html>
<body>
    <p>$$\frac{\pi}{2}$$</p>
    <script type="module">
       import MathLive from "https://unpkg.com/mathlive/dist/mathlive.min.mjs";
       MathLive.renderMathInDocument();
    </script>
</body>
</html>
```

**Comment by FlashTang** [comment] 2020-10-22 11:35
If I use local js file like so 
```
<!DOCTYPE html>
<html>
 
<body>
    <style> .ML__virtual-keyboard-toggle { color: red !important; } </style>
    <div id="mathfield">x=\frac{-b\pm \sqrt{b^2-4ac}}{2a}</div>
    
    <script  type="text/javascript" src="./js/mathlive.min.js"></script>
    <script type="text/javascript">
    	
    	MathLive.makeMathField(document.getElementById('mathfield'), { virtualKeyboardMode: 'manual' });

    	const newContent = document.createTextNode("Hi chrome and safari"); 
  
		  // add the text node to the newly created div
		document.body.appendChild(newContent);  

    </script>
</body>
</html>
```

> Ah, I got it, for the first error at least: you need to serve your `index.html` file from a local server, you can't open it as a local file. Due to CORS restrictions the assets (fonts in this case) cannot be loaded locally by the browser. And the (non-existent) error messages are not very helpful. If you want to use a `WKWebView`, [this article](https://medium.com/@zzdjk6/wkwebview-cors-solution-da20ca1194e8) contains info about how to configure it for this situation.

@arnog Hi arnog , I just use MAMP , and still the same error

![Screen Shot 2020-10-22 at 7 05 56 PM](https://user-images.githubusercontent.com/920751/96863728-e5082480-1499-11eb-80ee-d649f854bb15.png)


And another error I just found : 
If I use mathlive.min.js locally (whether with local host or not) 
The Chrome seems almost there (except messy font)
![Screen Shot 2020-10-22 at 5 59 00 PM](https://user-images.githubusercontent.com/920751/96864283-c0f91300-149a-11eb-8e30-38c64453a69f.png)
But error in Safari : 

![Screen Shot 2020-10-22 at 5 59 51 PM](https://user-images.githubusercontent.com/920751/96864492-159c8e00-149b-11eb-90fa-580648bc235e.png)
![Screen Shot 2020-10-22 at 6 00 41 PM](https://user-images.githubusercontent.com/920751/96864787-893e9b00-149b-11eb-9077-54ff668f620f.png)
So I change  `d || (c = e.match(/^["”“](.*?)["”“](.*)/)`  to `d || (c = e.match("abcd")`  at line 9250
And delete `if (/(^|[^a-zA-Z'’])[a-zA-Z][ ]$/.test(o)) return io(e, 1), !1;` at line 13974
Then safari can render like so without error  : 
![Screen Shot 2020-10-22 at 7 28 38 PM](https://user-images.githubusercontent.com/920751/96865939-2c43e480-149d-11eb-8b89-e1b80303a578.png)

Thanks

**Comment by FlashTang** [comment] 2020-10-22 11:48
> Ah, I got it, for the first error at least: you need to serve your `index.html` file from a local server, you can't open it as a local file. Due to CORS restrictions the assets (fonts in this case) cannot be loaded locally by the browser. And the (non-existent) error messages are not very helpful. If you want to use a `WKWebView`, [this article](https://medium.com/@zzdjk6/wkwebview-cors-solution-da20ca1194e8) contains info about how to configure it for this situation.
Thanks for the link , I will give it a try , and can you please check the error in Safari ( mentioned in above post )

**Comment by arnog** [comment] 2020-10-22 17:57
> @arnog Hi arnog , I just use MAMP , and still the same error

You need to use MAMP (or a similar local server) **AND** also set the fonts directory.

Try this (note the inclusion of the `fontsDirectory` option):
```html
<!DOCTYPE html>
<html>
 
<body>
    <style> .ML__virtual-keyboard-toggle { color: red !important; } </style>
    <div id="mathfield">x=\frac{-b\pm \sqrt{b^2-4ac}}{2a}</div>
    
    <script  type="text/javascript" src="./js/mathlive.min.js"></script>
    <script type="text/javascript">
    	
        MathLive.makeMathField(document.getElementById('mathfield'), 
        {
            virtualKeyboardMode: 'manual',
    	    fontsDirectory: '../fonts'
        }
        );

    	const newContent = document.createTextNode("Hi chrome and safari"); 
  
		  // add the text node to the newly created div
		document.body.appendChild(newContent);  

    </script>
</body>
</html>
```

I can't reproduce the Safari problem. Can you share the code that make it happen? Did you type something or do something to get the console errors or is it just when trying to display the formula?

**Comment by FlashTang** [comment] 2020-10-22 18:27
> > @arnog Hi arnog , I just use MAMP , and still the same error
> 
> You need to use MAMP (or a similar local server) **AND** also set the fonts directory.
> 
> Try this (note the inclusion of the `fontsDirectory` option):
> 
> ```
> <!DOCTYPE html>
> <html>
>  
> <body>
>     <style> .ML__virtual-keyboard-toggle { color: red !important; } </style>
>     <div id="mathfield">x=\frac{-b\pm \sqrt{b^2-4ac}}{2a}</div>
>     
>     <script  type="text/javascript" src="./js/mathlive.min.js"></script>
>     <script type="text/javascript">
>     	
>         MathLive.makeMathField(document.getElementById('mathfield'), 
>         {
>             virtualKeyboardMode: 'manual',
>     	    fontsDirectory: '../fonts'
>         }
>         );
> 
>     	const newContent = document.createTextNode("Hi chrome and safari"); 
>   
> 		  // add the text node to the newly created div
> 		document.body.appendChild(newContent);  
> 
>     </script>
> </body>
> </html>
> ```
> 
> I can't reproduce the Safari problem. Can you share the code that make it happen? Did you type something or do something to get the console errors or is it just when trying to display the formula?

@arnog I just figured it out 20 minute ago
Fixed all the issues mentioned above JUST after adding  html header (copied from somehere) to the html file 
so I think why ? ohhhh WHAT ? , there is `<meta charset="utf-8">` , this  charset="utf-8" fixed everything 
And I just tested in wk webview , perfectly works in iOS 13 ,although it still not working in the iOS 11 (mathlive.io also not working in iOS 11) , maybe I will try to find a way to debug it on iOS 11
Thank you very much for developping this awesome library and your  help !

**Comment by arnog** [comment] 2020-10-22 19:14
Very interesting. Glad you were able to get to the bottom of it. Would you know which default character encoding your browser was falling back to? And what is the locale of your browser? I'm not sure there's much I can do about this, but I'll add a note to the Getting Started guide.
Best of luck with your project, don't hesitate to reach out if you have questions.

**Comment by FlashTang** [comment] 2020-10-23 07:32
@arnog  
I can see the default character fallback of chrome  is **Western (Windows-1252)**. (determined with extension Chrome-Charset) ,locale - en-US ,zh-CN zh-TW and whatever I change the locale of browser to , the default fallback of chrome  always be **Western (Windows-1252)** , and I created the html file with sublime text , mac os 10.14 ,hope it helps
Thank you, you did a great job, I believe this is the best solution in  latex editor

**Comment by FlashTang** [comment] 2020-10-23 09:51
@arnog 
Just found a way to debug the js in wkwebview of iOS
Here is the error (the error only in iOS 11) ,ios13 no error , ios12 and ios14 not tested
SyntaxError: Unexpected token '...'. Expected a property name.
(anonymous function) — mathlive.min_1.js:2
Global Code — index.html:14
screenshoot of safari web inspector debug iOS 11 - index.html (loaded from iOS bundle by wkwebview)
![Screen Shot 2020-10-23 at 4 37 53 PM](https://user-images.githubusercontent.com/920751/96976335-4f7a9c80-154e-11eb-90ae-316cb274b14e.png)
And I search "..." 
![Screen Shot 2020-10-23 at 5 15 48 PM](https://user-images.githubusercontent.com/920751/96985978-9323d500-1553-11eb-9441-88aa06278e4d.png)
similar issue : https://github.com/sindresorhus/camelcase-keys/issues/45
https://www.cnblogs.com/thinkingthigh/p/11057079.html
Reason：browser does not support es6 extended spreads 
Conclusion：
1. do not use  ...
2. babel-polyfill not so good at ... spread operator，need to install a standalone **plugin-proposal-object-rest-spread**
Scene：ios 11.2 embedded wkwebview 
pc chrome is ok ，higher version ios is ok，one of the test devices - ios11.2 blank screen ,error  Unexpected token '...'. Expected a property name.

**Comment by arnog** [comment] 2020-10-23 11:18
>
> Here is the error (the error only in iOS 11) ,ios13 no error , ios12 and
> ios14 not tested
> SyntaxError: Unexpected token '...'.
>

Ah, indeed, that makes sense. MathLive supports the last two versions of
the major browsers. And Safari 11 doesn't support the spread operator,
which is used extensively thought the code base. Note that Safari 11.1,
released in March 2018, does.

If transpiling with Babel is not an option, something else to consider is
to recompile MathLive (which is written in Typescript) with the Typescript
compiler set to target an older version of JavaScript. I suspect there will
be other issues with JavaScript feature not supported by older browsers.

**Comment by FlashTang** [comment] 2020-10-23 14:08
> Here is the error (the error only in iOS 11) ,ios13 no error , ios12 and ios14 not tested SyntaxError: Unexpected token '...'.
> Ah, indeed, that makes sense. MathLive supports the last two versions of the major browsers. And Safari 11 doesn't support the spread operator, which is used extensively thought the code base. Note that Safari 11.1, released in March 2018, does. If transpiling with Babel is not an option, something else to consider is to recompile MathLive (which is written in Typescript) with the Typescript compiler set to target an older version of JavaScript. I suspect there will be other issues with JavaScript feature not supported by older browsers.

👍

**Comment by arnog** [comment] 2020-11-02 08:21
No activity on this thread in a week. Closing. Please re-open or open a new issue if you have any follow up questions.

**Closed by arnog** 2020-11-02 08:21 UTC
Labels: unable to reproduce

**Comment by dlpigpen** [comment] 2020-11-06 09:16
I got the same error in iPhone Agent. I was not able to type or the keyboard does not appear after focusing the math text field. Here is the log I got from the browser.
<img width="649" alt="Screen Shot 2020-11-06 at 16 14 47" src="https://user-images.githubusercontent.com/5404685/98348424-4f4cc780-204b-11eb-9978-6d49c1ec6c8f.png">

**Comment by arnog** [comment] 2020-11-06 13:15
@dlpigpen could you provide a bit more info?
- I don't know what 'iPhone X Agent' is
- which version of iOS are you using?
- can you try using the debug version of MathLive and report what error you are getting (i.e. `mathlive.js` instead of `mathlive.min.js`)
- did you do any bundling of the `mathlive.min.js` file (i.e. using Webpack or Babel)?

**Comment by dlpigpen** [comment] 2020-11-06 13:48
@arnog 
- I tested on the Safari browser and simulated using the "iPhone X" agent.
- "manual" works fine when I click on the "button" keyboard. The "focus" or "auto" does not appear when the text field is focusing.
- mathlive.js has the same result. There is no virtual keyboard 
- I only follow the example. I have not applied for any new building. 
![Uploading Screen Shot 2020-11-06 at 20.44.12.png…]()

**Comment by arnog** [comment] 2020-11-06 15:11
@dlpigpen 
- when using `mathlive.js` do you get the same output in the console log? ("Uncaught type error...")?
- Which version of Safari are you using? 
- Could you give me some instruction on how to get to this emulator? I don't know how to get to that Settings panel in Safari.
- Do you have your code somewhere I could have a look at, or a CodePen?
