### ISSUE TITLE
MathML export: missing bracket

### ISSUE THREAD

**Issue by fmp-km** [arnog/mathlive#2045] opened 2023-07-03 10:48 UTC
## Description

some MathML miss right angle bracket

## Steps to Reproduce

1. Enter `\left(a+b\right)^2`
2. export with `...getValue("math-json")`  or with `mathlive.convertLatexToMathMl(expr);`

### Actual Behavior

math-ml shows up as  "a+b)²"

this is as a right angle bracket is missing after "<mo":
`<msup><mrow><mo(</mo><mrow><mi>a</mi><mo>+</mo><mi>b</mi></mrow><mo>)</mo></mrow><mn>2</mn></msup>`

### Environment

MathLive 0.94.8

Lunux Ubuntu 20.04.6 LTS

tested with Firefix 112.0.2 and Chrome108.0.5359.98

**Comment by arnog** [comment] 2023-07-04 18:55
Duplicate of #1996

**Closed by arnog** 2023-07-04 18:55 UTC
Labels: duplicate
