### ISSUE TITLE
Styles disappear after insert is applied

### ISSUE THREAD

**Issue by poincare15** [arnog/mathlive#2260] opened 2024-01-13 18:55 UTC
Step - 1: Write anything 
Step - 2: Apply a style (color, background etc.)
Step - 3: Select the text.
Step - 4:  Apply insert (sqrt, frac etc.)

Your applied styles disappear (colors, background, size, \displaystyle etc. removed)

Is this a bug?

![style_bug](https://github.com/arnog/mathlive/assets/134855855/f6971a1a-1264-43c6-9039-0da361efe0c5)

Mathlive version: 0.98.5
Browser: Chrome 120
OS: Windows 11

**Comment by arnog** [comment] 2024-01-13 20:00
Duplicate of #2104

**Comment by arnog** [comment] 2024-05-22 21:28
A detail worth adding: this happens if you select from right to left. If you select from left to right, you get the expected result.

**Comment by poincare15** [comment] 2024-05-22 21:50
> A detail worth adding: this happens if you select from right to left. If you select from left to right, you get the expected result.

Interestingly I got the same error in bug directions. I think I'm doing something wrong.

My solution: 
**replace 'latex-unstyled' with 'latex'**

https://github.com/arnog/mathlive/blob/7860e5054eed2b185997d3cd6f669bc7610e5c91/src/editor-mathfield/mode-editor-math.ts#L217

I solved it this way. I hope I didn't break anything else.

**Comment by arnog** [comment] 2024-05-22 22:28
That seems to be a different problem. I don't think this code path is used when following the steps in this bug report (i.e. selecting a subexpression, then typing something on the keyboard to replace it). It may be that using `latex` instead of `latex-unstyled` might be OK. I'll need to think about it.

**Closed** 2024-05-23 16:38 UTC
Labels: bug, Sponsored
